- pkg/vit/mock/impl.go
(small update to vit/mock: Elements() added to Object mock)
> Migrate system sources from bp3 to voedger  (#119)

- go.mod
- pkg/iauthnzimpl/consts.go
Resolves #795 ACL: rename `sys.Login` -> `registry.Login`
> #795 ACL: rename `sys.Login` -> `registry.Login`

- pkg/registry/impl_issueprincipaltoken.go
- pkg/registry/utils.go
Resolves #804 investigate "`sys.Login` not found" error
> #804 investigate "`sys.Login` not found" error

- pkg/registry/utils.go
Resolves #806 investigate "`sys.Login` not found" error 2
> #806 investigate "`sys.Login` not found" error 2

- pkg/apps/sys/registryapp/provide.go
Resolves #856 Fix typo: `regfistryapp`
> #856 Fix typo: `regfistryapp`

- pkg/sys/sqlquery/impl_plog.go
- pkg/utils/utils.go
- pkg/vvm/impl_appws.go
Resolves #870 move `PartitionID` computation to `coreutils`
> #870 move `PartitionID` computation to `coreutils`

- pkg/processors/command/impl.go
Resolves #882 wrong cmd exec duration computation
> #882 wrong cmd exec duration computation

- pkg/sys/uniques/consts.go
- pkg/sys/uniques/impl.go
- pkg/sys/uniques/provide.go
- pkg/sys/uniques/utils.go
Resolves #911 name conflict `view.sys.Uniques` and `p.sys.Uniques`
> #911 name conflict `view.sys.Uniques` and `p.sys.Uniques`

- pkg/parser/impl_analyse.go
- pkg/parser/impl_test.go
Resolves #913 sql: nil pointer dereference on parsing a VIEW without PRIMARY KEY
> #913 sql: nil pointer dereference on parsing a VIEW without PRIMARY KEY

- pkg/parser/impl_analyse.go
- pkg/parser/impl_test.go
Resolves #837 sql: impossible to specify odoc with orecord as an arg of a func
> #837 sql: impossible to specify odoc with orecord as an arg of a func

- pkg/sys/sys.sql
Resolves #932 rename `sys.SendEmailVerificationCodeParams` -> `sys.SendEmailVerificationParams`
> #932 rename `sys.SendEmailVerificationCodeParams` -> `sys.SendEmailVerificationParams`

- pkg/sys/sys.sql
Resolves #951 define `c.sys.CUD` and deprecated `c.sys.Init` in sql
> #951 define `c.sys.CUD` and deprecated `c.sys.Init` in sql

- pkg/processors/query/impl.go
Resolves #1006 fix query processor: wrong "Body" field type on Raw Arg
> #1006 fix query processor: wrong "Body" field type on Raw Arg

- pkg/processors/command/impl.go
- pkg/processors/command/provide.go
- pkg/sys/builtin/impl_sysisactivevalidation.go
Resolves #1125 deny `sys.IsActive` + other fields update in client CUDs only, allow in result CUDs of commands
> #1125 deny `sys.IsActive` + other fields update in client CUDs only, allow in result CUDs of commands

- cmd/vpm/compile.go
Resolves #1155 `vpm baseline` produces `%5` in paths on Windows
> #1155 `vpm baseline` produces `%5` in paths on Windows

- cmd/vpm/baseline.go
- cmd/vpm/const.go
> 1166 baselinejsontimestamp use gmt with milliseconds httpspkggodevtimetimeformat

- pkg/utils/verificationcode.go
Resolves #1182 fix copyright of `utils/verificationcode.go`
> #1182 fix copyright of `utils/verificationcode.go`

- pkg/parser/errors.go
- pkg/parser/impl_analyse.go
- pkg/parser/impl_build.go
- pkg/parser/utils.go
Resolves #1157 need clear error description instead of panic in parser (`unexpected root table kind 0`)
> #1157 need clear error description instead of panic in parser (`unexpected root table kind 0`)

- pkg/parser/impl.go
- pkg/parser/impl_test.go
Resolves #1237 `vpm compile` panics: `AppSchemaAST` built with errors could cause panic in `parser.BuildAppSchema()`
> #1237 `vpm compile` panics: `AppSchemaAST` built with errors could cause panic in `parser.BuildAppSchema()`

- pkg/parser/impl_analyse.go
- pkg/parser/impl_test.go
- pkg/parser/utils.go
Resolves #1299 parser: `projector after insert` on the workspace descriptor causes `unknown table` error
> #1299 parser: `projector after insert` on the workspace descriptor causes `unknown table` error

- cmd/ctool/backup.go
- cmd/ctool/cluster.go
- cmd/ctool/scripts/drafts/utils.sh
Resolves #1397 ctool replace: check that backup folder exists and accessible
> #1397 ctool replace: check that backup folder exists and accessible

- pkg/projectors/async.go
Resolves #1442 eliminate panic if the projector is not defined in sql
> #1442 eliminate panic if the projector is not defined in sql

- pkg/vit/impl.go
- pkg/vit/utils.go
Resolves #1449 VIT: additional fixes to initializing childs of child workspaces
> #1449 VIT: additional fixes to initializing childs of child workspaces

- pkg/istructsmem/appstruct-types.go
- pkg/istructsmem/appstruct-types_test.go
- pkg/processors/command/impl_test.go
- pkg/projectors/async_test.go
- pkg/projectors/impl_test.go
- pkg/sys/collection/collection_test.go
- pkg/sys/it/impl_test.go
- pkg/sys/it/testapp.sql
- pkg/vit/shared_cfgs.go
- pkg/vvm/provide.go
- pkg/vvm/wire_gen.go
Resolves #1462 VVM: validate if correct execs are provided for funcs and projectors defined in vSQL and vice versa
> #1462 VVM: validate if correct execs are provided for funcs and projectors defined in vSQL and vice versa

- pkg/vit/impl.go
- pkg/vvm/impl_cfg.go
Resolves #1549 VVM: use TestSecretsReader if running tests
> #1549 VVM: use TestSecretsReader if running tests

- pkg/sys/it/impl_workspace_test.go
- pkg/sys/workspace/impl_childworkspace.go
- pkg/sys/workspace/provide.go
Resolves #1563 revert: do not allow to create workspaces with kidn that is not QName of descriptor
> #1563 revert: do not allow to create workspaces with kind that is not QName of descriptor

- pkg/vvm/impl_requesthandler.go
Resolves #1588 temporary fix: return 503 if partitions are not deployed yet
> #1588 temporary fix: return 503 if partitions are not deployed yet

- pkg/projectors/async.go
- pkg/projectors/consts.go
Resolves #1619 async actualizers: log error if failed to init in 30 seconds
> #1619 async actualizers: log error if failed to init in 30 seconds

- pkg/vvm/provide.go
- pkg/vvm/types.go
- pkg/vvm/wire_gen.go
Resolves #1625 amount of actualizers must be defined by `DeploymentDescriptor.PartsCount`, not by the amount of command processors
> #1625 amount of actualizers must be defined by `DeploymentDescriptor.PartsCount`, not by the amount of command processors

- pkg/sys/it/impl_workspace_test.go
- pkg/sys/workspace/impl_childworkspace.go
- pkg/sys/workspace/provide.go
Resolves #1622 re-implement: do not allow to create workspaces with kinds that is not QName of descriptor
> #1622 re-implement: do not allow to create workspaces with kinds that is not QName of descriptor

- pkg/processors/query/impl.go
Resolves #1637 QP: return error if `IWorkspace` is not found by `WorkspaceDescriptor.WSKind`
> #1637 QP: return error if `IWorkspace` is not found by `WorkspaceDescriptor.WSKind`

- cmd/vpm/main_test.go
- pkg/apps/consts.go
- pkg/iauthnzimpl/impl.go
- pkg/iauthnzimpl/impl_test.go
- pkg/iauthnzimpl/provide.go
- pkg/iauthnzimpl/types.go
- pkg/iauthnzimpl/utils.go
- pkg/processors/command/impl_test.go
- pkg/processors/query/impl_test.go
- pkg/processors/query/query-params-impl_test.go
- pkg/sys/collection/collection_test.go
- pkg/sys/it/impl_signupin_test.go
- pkg/vvm/provide.go
- pkg/vvm/wire_gen.go
Resolves #1678 voedger: provide additional device authnz processing funcs instead of use air-related stuff in voedger
> #1678 voedger: provide additional device authnz processing funcs instead of use air-related stuff in voedger

- pkg/sys/it/impl_invite_test.go
Resolves #1720 fix TestInvite_BasicUsage()
> #1720 fix TestInvite_BasicUsage()

- pkg/vit/impl.go
Resolves #1725 VIT: fix delay on IAppStorage.Get()
> #1725 VIT: fix delay on IAppStorage.Get()

- cmd/ctool/scripts/drafts/set-cron-backup.sh
Resolves #1742 ctool backup cron bug for the root user
> #1742 ctool backup cron bug for the root user

- pkg/utils/mock.go
Resolves #1760 testing: implement ToBytes() methods for mocks
> #1760 testing: implement ToBytes() methods for mocks

- pkg/vvm/metrics/impl.go
- pkg/vvm/metrics/provide.go
- pkg/vvm/metrics/types.go
Resolves #1757 VVM: make so metrics service will not start to listen on Provide(). Listen on Prepare() instead
> #1757 VVM: make so metrics service will not start to listen on Provide(). Listen on Prepare() instead

- pkg/utils/mock.go
Resolves #1787 voedger VIT mocks: implement `IState.App()`
> #1787 voedger VIT mocks: implement `IState.App()`

- pkg/processors/command/impl.go
- pkg/sys/workspace/impl.go
- pkg/sys/workspace/utils.go
- pkg/utils/maps.go
- pkg/utils/maps_test.go
Resolves #1799 coreutils: rename Marshal() -> MapToObject()
> #1799 coreutils: rename Marshal() -> MapToObject()

- pkg/sys/workspace/impl_deactivate.go
- pkg/sys/workspace/provide.go
Resolves #1806 asp.DeactivateWorkspace: must use IState, not use IAppStructsProvider
> #1806 asp.DeactivateWorkspace: must use IState, not use IAppStructsProvider

- cmd/ctool/consts.go
- cmd/ctool/utils.go
Resolves #1755 ctool: optimize `log` folders
> #1755 ctool: optimize `log` folders

- pkg/utils/files.go
Resolves #1923 coreutils: CopyDirFS: creat target path with rwxrwxrwx, not from "." FileMode
> #1923 coreutils: CopyDirFS: creat target path with rwxrwxrwx, not from "." FileMode

- pkg/router/impl_blob.go
Resolves #1939 panic on Test cluster: Header called after Handler finished
> #1939 panic on Test cluster: Header called after Handler finished

- pkg/cluster/impl_deployapp.go
- pkg/vvm/types.go
- pkg/vvm/wire_gen.go
Resolves #1974 VVM APIs: eliminate `vvm.VVM.IAppStorageFactory`
> #1974 VVM APIs: eliminate `vvm.VVM.IAppStorageFactory`

- pkg/utils/maps.go
- pkg/utils/maps_test.go
Resolves #1992 coreutils: consider non-float64 numbers on coreutils.MapToObject()
> #1992 coreutils: consider non-float64 numbers on coreutils.MapToObject()

- pkg/processors/query/filter-equals-impl.go
- pkg/processors/query/filter-equals-impl_test.go
https://dev.untill.com/projects/#!691710
> queryprocessor: improve equals filter

- pkg/btstrp/consts.go
Resolves #2012 bootstrap: skip error on cluster requests during up to 30 seconds
> #2012 bootstrap: skip error on cluster requests during up to 30 seconds

- pkg/sys/it/impl_resetpassword_test.go
- pkg/sys/it/impl_verifier_test.go
- pkg/sys/verifier/impl.go
Resolves #2027 return back rate limit on `c.sys.InitiateEmailVerification`
> #2027 return back rate limit on `c.sys.InitiateEmailVerification`

- pkg/sys/blobber/types.go
- pkg/sys/it/impl_blob_test.go
- pkg/sys/workspace/impl.go
- pkg/utils/federation/impl.go
- pkg/utils/federation/interface.go
- pkg/utils/types.go
- pkg/vit/impl.go
Resolves #2095 avoid import cycle on using IFederation from `state` package
> #2095 avoid import cycle on using IFederation from `state` package

- pkg/state/impl_federation_cmd_storage.go
Resolves #2173 FederationCommandStorage: doesn't work in the emulation mode
> #2173 FederationCommandStorage: doesn't work in the emulation mode

- pkg/iextengine/wazero/_testdata/tests/main_test.go
Resolves #2180 iextenginewazero: basic usage test fails
> #2180 iextenginewazero: basic usage test fails

- pkg/sys/sqlquery/impl.go
- pkg/sys/sqlquery/impl_plog.go
Resolves #2190 SqlQuery: panic on read event -> render the error message as `!!!Panic` result field
> #2190 SqlQuery: panic on read event -> render the error message as `!!!Panic` result field

- pkg/state/teststate/testsys/system.sql
Resolves #2184 teststate: cdoc.ChildWorkspace not available
> #2184 teststate: cdoc.ChildWorkspace not available

- pkg/istructsmem/event-types.go
- pkg/istructsmem/event-types_test.go
- pkg/istructsmem/types.go
- pkg/istructsmem/types_test.go
Resolves #2211 istructsmem: panic in `FillFromJSON` and `PutFromJSON` -> collect errors
> #2211 istructsmem: panic in `FillFromJSON` and `PutFromJSON` -> collect errors

- pkg/sys/invite/impl_applyjoinworkspace.go
- pkg/sys/it/impl_childworkspace_test.go
- pkg/sys/it/impl_workspace_test.go
- pkg/sys/workspace/impl.go
- pkg/sys/workspace/impl_deactivate.go
- pkg/vit/utils.go
Resolves #2217 workspace creation: `WSName` is not escaped
> #2217 workspace creation: `WSName` is not escaped

- pkg/state/types.go
Resolves #2231 StorageResult: invalid memory address issue when using in tests
> #2231 StorageResult: invalid memory address issue when using in tests

- pkg/processors/command/impl.go
- pkg/processors/command/impl_test.go
- pkg/processors/command/provide.go
Resolves #2295 deny `cuds` JSON field for all commands except `c.sys.CUD`
> #2295 deny `cuds` JSON field for all commands except `c.sys.CUD`

- pkg/router/impl_test.go
Resolves #2300 fix TestClientDisconnect_FailedToWriteResponse() test
> #2300 fix TestClientDisconnect_FailedToWriteResponse() test

- pkg/state/errors.go
- pkg/sys/it/impl_test.go
Resolves #2302 Dedicated error for "qname is not defined in the workspace"
> #2302 Dedicated error for "qname is not defined in the workspace"

- pkg/iauthnzimpl/consts.go
- pkg/iauthnzimpl/impl_acl.go
Resolves #2377 ACL: add q.air.GetResellers null auth
> #2377 ACL: add q.air.GetResellers null auth

- pkg/iauthnzimpl/consts.go
- pkg/iauthnzimpl/impl.go
- pkg/iauthnzimpl/impl_test.go
- pkg/istructs/consts.go
Resolves #2468 authnz: emit user principal with `sys.Guest` login if token is not provided
> #2468 authnz: emit user principal with `sys.Guest` login if token is not provided

- pkg/iauthnzimpl/consts.go
- pkg/iauthnzimpl/impl_acl.go
Resolves #2470 grant exec on q.sys.State to role.air.BOReader
> #2470 grant exec on q.sys.State to role.air.BOReader

- pkg/iauthnzimpl/impl.go
Resolves #2476 authnz: no token -> read roles for `sys.Guest` from subjects if any
> #2476 authnz: no token -> read roles for `sys.Guest` from subjects if any

- pkg/dml/types.go
- pkg/sys/it/impl_sqlquery_test.go
- pkg/sys/sqlquery/impl.go
- pkg/utils/http.go
Resolves #2498 sqlquery: select * from <wsid>.wlog returns the first record only
> #2498 sqlquery: select * from <wsid>.wlog returns the first record only

- pkg/istorage/provider/provide.go
- pkg/utils/utils.go
- pkg/vvm/types.go
Resolves #2525 VIT: keyspace names must be unique among Own VIT Configs
> #2525 VIT: keyspace names must be unique among Own VIT Configs

- pkg/utils/http.go
Resolves #2529 refactor `HTTPResponse.Println()`
> #2529 refactor `HTTPResponse.Println()`

- pkg/state/teststate/interface.go
Resolves #2583 testapi: return back IIntentAssertions.NotExists()
> #2583 testapi: return back IIntentAssertions.NotExists()

- pkg/state/teststate/impl.go
> 2587 wsid for commandprocessor kind returns 0 in tests using exttinygotestsnewtestapi

- pkg/state/stateprovide/impl_query_processor_state.go
- pkg/state/stateprovide/impl_query_processor_state_test.go
Resolves #2589 QueryProcessorState: FindIntent doesn't work for sys.Result
> #2589 QueryProcessorState: FindIntent doesn't work for sys.Result

- cmd/ctool/alert.go
- cmd/ctool/backup.go
- cmd/ctool/init.go
- cmd/ctool/main.go
- cmd/ctool/mon.go
- cmd/ctool/repeat.go
- cmd/ctool/replace.go
- cmd/ctool/restore.go
- cmd/ctool/scripts.go
- cmd/ctool/upgrade.go
- cmd/ctool/utils.go
- cmd/ctool/validate.go
- pkg/goutils/cobrau/rootcmd.go
Resolves #2597 The `verbose` and `trace` flags do not apply to subcommands
> #2597 The `verbose` and `trace` flags do not apply to subcommands

- pkg/iextengine/wazero/impl.go
Resolves #2599 sidecar app panic: i32.trunc_sat_f64_s invalid as feature "nontrapping-float-to-int-conversion" is disabled
> #2599 sidecar app panic: i32.trunc_sat_f64_s invalid as feature "nontrapping-float-to-int-conversion" is disabled

- pkg/exttinygo/internal/impl_tinygo.go
Resolves #2602 sidecar app panic: "hostRowWriterPutIntBool" is not exported in module "env"
> #2602 sidecar app panic: "hostRowWriterPutIntBool" is not exported in module "env"

- pkg/processors/actualizers/async.go
Resolves #2607 actualizers: skip projectors that are not defined in the workspace of the event: eliminate double check
> #2607 actualizers: skip projectors that are not defined in the workspace of the event: eliminate double check

- pkg/sys/it/impl_workspace_test.go
- pkg/sys/workspace.vsql
- pkg/sys/workspace/impl_childworkspace.go
Resolves #2638 c.sys.InitChildWorkspace: make WSClusterID not required
> #2638 c.sys.InitChildWorkspace: make WSClusterID not required

- pkg/vit/mock/impl.go
Resolves #2642 VIT: make so `mock.StateKeyBuilder` implement `fmt.Stringer()` interface
> #2642 VIT: make so `mock.StateKeyBuilder` implement `fmt.Stringer()` interface

- .golangci.yml
- pkg/processors/actualizers/async.go
- pkg/processors/actualizers/async_test.go
Resolves #2670 Redundant logging of the errors in async actualizer
> #2670 Redundant logging of the errors in async actualizer

- pkg/coreutils/time.go
Resolves #2678 coreutilsMockTime: decrease by 5 minutes
> #2678 coreutilsMockTime: decrease by 5 minutes

- pkg/iextengine/wazero/impl.go
Resolves #2694 rand.Reader returns the same sequence in different engine instances
> #2694 rand.Reader returns the same sequence in different engine instances

- pkg/appparts/impl_app.go
- pkg/objcache/provide.go
Resolves #2734 IAppPartition may be not returned to the pool
> #2734 IAppPartition may be not returned to the pool

- pkg/processors/actualizers/impl.go
- pkg/processors/actualizers/interface.go
- pkg/processors/actualizers/provide.go
Resolves #1823 sync actualizer state: should use `AppStructs()` from borrowed partition
> #1823 sync actualizer state: should use `AppStructs()` from borrowed partition

- pkg/router/provide.go
- pkg/router/utils.go
Resolves #2749 eliminate annoying `http: TLS handshake error from 10.0.0.2:31842: tls: first record does not look like a TLS handshake` log messages
> #2749 eliminate annoying `http: TLS handshake error from 10.0.0.2:31842: tls: first record does not look like a TLS handshake` log messages

- pkg/coreutils/mapobject.go
- pkg/processors/command/impl.go
- pkg/processors/command/impl_test.go
- pkg/processors/query/query-params-impl_test.go
Resolves #2769 CP: use `MapObject.AsObject()` for `args` and `unloggedArgs`
> #2769 CP: use `MapObject.AsObject()` for `args` and `unloggedArgs`

- pkg/processors/command/impl.go
- pkg/registry/impl_createlogin.go
- pkg/sys/it/impl_signupin_test.go
Resolves #2791 `c.registry.CreateLogin`: deny for an undeployed app
> #2791 `c.registry.CreateLogin`: deny for an undeployed app

- pkg/istructsmem/errors.go
- pkg/istructsmem/event-types.go
- pkg/istructsmem/event-types_test.go
- pkg/processors/command/impl.go
- pkg/processors/command/provide.go
- pkg/sys/it/impl_test.go
- pkg/sys/it/impl_uniques_test.go
- pkg/vit/schemaTestApp1.vsql
Resolves #2784 CP: do not allow `null` values in requests
> #2784 CP: do not allow `null` values in requests

- pkg/appparts/internal/actualizers/actualizers.go
- pkg/appparts/internal/schedulers/schedulers.go
- pkg/processors/actualizers/async_test.go
Resolves #2844 checking if a goroutine has started each nanosecond causes very long awaiting on Linux
> #2844 checking if a goroutine has started each nanosecond causes very long awaiting on Linux

- pkg/appdef/impl_appdef.go
- pkg/appdef/impl_type.go
- pkg/appdef/impl_workspace.go
- pkg/appdef/impl_workspace_test.go
- pkg/appdef/interface_workspace.go
- pkg/appdef/utils_qname.go
- pkg/appdef/utils_qname_test.go
Resolves #2845 appdef: IWorkspace.Types should be order by QName
> #2845 appdef: IWorkspace.Types should be order by QName

- pkg/sys/invite/impl_initiatejoinworkspace.go
- pkg/sys/it/impl_invite_test.go
- pkg/sys/it/test_utils.go
Resolves #2952 c.sys.InitiateJoinWorkspace: new error: token login does not match invite login
> #2952 c.sys.InitiateJoinWorkspace: new error: token login does not match invite login

- pkg/iauthnz/authn-types.go
- pkg/sys/it/testdata/apps/test2.app1/image/pkg/github.com/voedger/sidecartestapp/schema_ws.vsql
- pkg/sys/it/testdata/apps/test2.app1/image/pkg/sys/sys.vsql
- pkg/sys/it/testdata/apps/test2.app1/src/schema_ws.vsql
- pkg/sys/sys.vsql
- pkg/vit/schemaTestApp1.vsql
Resolves #2954 grant WorkspaceOwner to RoleWorkspaceOwner for backward compatibility
> #2954 grant WorkspaceOwner to RoleWorkspaceOwner for backward compatibility

- cmd/ctool/scripts.go
Resolves #2263 ctool: Error: open scripts\drafts: file does not exist
> #2263 ctool: Error: open scripts\drafts: file does not exist

- pkg/router/impl_apiv2.go
Resolves #2993 Router: read from CDocs collection: url path: `docs` -> `cdocs`
> #2993 Router: read from CDocs collection: url path: `docs` -> `cdocs`

- pkg/processors/command/impl.go
- pkg/sys/workspace/impl.go
Resolves #3041 CP: skip work with `WorkspaceDescriptor` on `c.sys.CreateWorkspaceID`
> #3041 CP: skip work with `WorkspaceDescriptor` on `c.sys.CreateWorkspaceID`

- pkg/istorage/cas/impl.go
- pkg/istorage/interface.go
- pkg/istorage/mem/impl.go
- pkg/istorage/tck.go
> 3083 insertifnotexistscompareandswap method must insert persistent key if ttl is zero 1

- pkg/cluster/appws.vsql
Resolves #3111 vsql update query field: max default len 255
> #3111 vsql update query field: max default len 255

- pkg/processors/command/impl.go
Resolves #3163 CP: expose current user principal name in the command processor workpiece
> #3163 CP: expose current user principal name in the command processor workpiece

- pkg/processors/command/impl.go
- pkg/sys/it/impl_cud_test.go
- pkg/sys/it/impl_test.go
Resolves #3182 CP: clarify the error message if `sys.QName` on insert is missing
> #3182 CP: clarify the error message if `sys.QName` on insert is missing

- pkg/sys/it/impl_sqlquery_test.go
- pkg/sys/sqlquery/impl.go
Resolves #3281 q.sys.SqlQuery in different app: forward with sys token -> forward with the provided token re-issued for the target app
> #3281 q.sys.SqlQuery in different app: forward with sys token -> forward with the provided token re-issued for the target app

- pkg/vvm/provide.go
- pkg/vvm/ttlstorage/impl.go
- pkg/vvm/wire_gen.go
Resolves #3310 ITTLStorage must work on sysvvm keyspace
> #3310 ITTLStorage must work on `sysvvm` keyspace

- pkg/vvm/impl_orch.go
- pkg/vvm/impl_orch_test.go
Resolves #3332 do panic on VVM.Shutdown() if VVM.Launch() was not called
> #3332 do panic on VVM.Shutdown() if VVM.Launch() was not called

- pkg/processors/query2/const.go
Resolves #3420 qpv2: declare `/schemas` paths
> #3420 qpv2: declare `/schemas` paths

- pkg/bus/impl.go
- pkg/bus/impl_test.go
- pkg/bus/interface.go
- pkg/bus/utils.go
- pkg/router/impl_test.go
Resolves #3445 Provide response meta to `IResponder.Respond()`
> #3445 Provide response meta to `IResponder.Respond()`

- pkg/router/impl_reply_v1.go
Resolves #3450 router: fix `{}` rendering on empty response
> #3450 router: fix `{}` rendering on empty response

- pkg/processors/query2/impl.go
- pkg/router/impl_reply_v2.go
Resolves #3460 router: explicitly use zero Partition on paths without WSID
> #3460 router: explicitly use zero Partition on paths without WSID

- pkg/processors/query2/impl.go
- pkg/processors/query2/impl_schemas_handler.go
- pkg/processors/query2/impl_schemas_roles_handler.go
- pkg/sys/it/impl_qpv2_test.go
Resolves #3340 GET `/schemas/{workspace}/roles`: return the list of published roles
> #3340 GET `/schemas/{workspace}/roles`: return the list of published roles

- pkg/processors/query2/impl_openapi.go
- pkg/processors/query2/impl_schemas_role_handler.go
- pkg/sys/it/impl_qpv2_test.go
- pkg/vit/schemaTestApp1.vsql
Resolves #3465 schemas: use role comment as an OpenApi description
> #3465 schemas: use role comment as an OpenApi description

- pkg/parser/impl_analyse.go
- pkg/parser/impl_test.go
- pkg/parser/sql_example_app/pmain/package.vsql
- pkg/parser/types.go
Resolves #3471 parser: unable to use `sys.*` fields in GRANTS
> #3471 parser: unable to use `sys.*` fields in GRANTS

- pkg/istructs/consts.go
- pkg/istructs/consts_test.go
Resolves #3528 fix istructs.ClusterAsRegisterID iota usage
> #3528 fix istructs.ClusterAsRegisterID iota usage

- pkg/isequencer/isequencer_test.go
Resolves #3590 fix typo in TestSequencer_Start
> #3590 fix typo in TestSequencer_Start

- pkg/coreutils/random.go
- pkg/coreutils/random_test.go
- pkg/router/consts.go
- pkg/router/impl_apiv2.go
- pkg/sys/it/bug_test.go
- pkg/sys/it/impl_signupin_test.go
- pkg/vit/utils.go
Resolves #3610 Fix /devices result and argsResolves issue 'CPv2: handle `/devices`'Resolves #3565 CPv2: handle `/devices`
> #3610 Fix /devices result and argsissue 'CPv2: handle `/devices`'#3565 CPv2: handle `/devices`

- pkg/coreutils/federation/impl.go
- pkg/coreutils/federation/interface.go
- pkg/coreutils/federation/provide.go
- pkg/coreutils/federation/types.go
- pkg/coreutils/http.go
- pkg/processors/query2/impl.go
- pkg/processors/query2/impl_auth_login_handler.go
- pkg/processors/query2/impl_auth_refresh_handler.go
- pkg/processors/query2/interface.go
- pkg/processors/query2/util.go
- pkg/router/impl_apiv2.go
- pkg/vvm/provide.go
- pkg/vvm/wire_gen.go
Resolves #3623 /auth: relocate handling from router to QPv2 + eliminate retries on query from QP
> #3623 /auth: relocate handling from router to QPv2 + eliminate retries on query from QP

- pkg/vit/impl.go
- pkg/vvm/impl_cfg.go
Resolves #3644 VIT: force `SequencesTrustLevel_0`
> #3644 VIT: force `SequencesTrustLevel_0`

- pkg/cluster/appws.vsql
- pkg/parser/errors.go
- pkg/parser/impl_analyse.go
- pkg/parser/impl_test.go
- pkg/parser/types.go
Resolves #3706 parser: BLOB field can be only added to documents or records
> #3706 parser: BLOB field can be only added to documents or records

- pkg/coreutils/federation/impl.go
- pkg/coreutils/federation/utils.go
- pkg/router/impl_n10n.go
Resolves #3750 APIv2 notifications: extract router serve SSE and client-side read SSe routine
> #3750 APIv2 notifications: extract router serve SSE and client-side read SSE routine

- pkg/state/stateprovide/impl_async_actualizer_state.go
- pkg/state/stateprovide/impl_scheduler_state.go
- pkg/state/types.go
- pkg/sys/invite/impl_applyinvitation.go
- pkg/sys/invite/impl_applyupdateinviteroles.go
- pkg/sys/storages/impl_send_mail_storage.go
- pkg/sys/verifier/impl.go
- pkg/vit/impl.go
- pkg/vit/impl_test.go
- pkg/vit/shared_cfgs.go
Resolves #3808 Invites: eliminate coreutils.IsTest usage on loading the mailer pwd secret
> #3808 Invites: eliminate coreutils.IsTest usage on loading the mailer pwd secret

- pkg/coreutils/json_test.go
Resolves #3837 implement tests for coreutils `ClarifyJSONWSID` and `JSONUnmarshalDisallowUnknownFields`
> #3837 implement tests for coreutils `ClarifyJSONWSID` and `JSONUnmarshalDisallowUnknownFields`

- pkg/sys/it/impl_test.go
Resolves #3849 Put in order skipped tests in TestTakeQNamesFromWorkspace
> #3849 Put in order skipped tests in TestTakeQNamesFromWorkspace

- pkg/sys/builtin/impl_refintegrity.go
- pkg/sys/it/impl_cpv2_test.go
- pkg/sys/it/impl_cud_test.go
- pkg/sys/it/impl_qpv2_test.go
- pkg/sys/it/impl_recovery_test.go
- pkg/sys/it/impl_sqlquery_test.go
- pkg/vit/schemaTestApp1.vsql
[AIR-1257] voedger: fix referential integrity checking in ORecords
https://untill.atlassian.net/browse/AIR-1257
> voedger: fix referential integrity checking in ORecords

- pkg/isequencer/consts.go
- pkg/isequencer/test_utils.go
Resolves #4038 fix TestISequencer_FlushPermanentlyFails
> fix TestISequencer_FlushPermanentlyFails

- pkg/coreutils/consts.go
- pkg/coreutils/utils.go
- pkg/istorage/provider/test_utils.go
- pkg/processors/blobber/impl_read.go
- pkg/processors/blobber/impl_write.go
- pkg/router/consts.go
- pkg/router/provide.go
- pkg/router/types.go
- pkg/vit/impl.go
- pkg/vvm/consts.go
- pkg/vvm/impl_cfg.go
- pkg/vvm/types.go
Resolves #4068 get rid of `IsTest()` usage in router on defining the Admin endpoint port
> get rid of `IsTest()` usage in router on defining the Admin endpoint port

- pkg/coreutils/federation/impl.go
- pkg/coreutils/federation/impl_test.go
- pkg/coreutils/federation/provide.go
- pkg/coreutils/federation/utils.go
- pkg/coreutils/http.go
- pkg/coreutils/http_test.go
- pkg/coreutils/types.go
- pkg/sys/it/bug_test.go
- pkg/sys/it/impl_blob_test.go
- pkg/sys/it/impl_cpv2_test.go
- pkg/sys/it/impl_cud_test.go
- pkg/sys/it/impl_httpconventions_test.go
- pkg/sys/it/impl_invite_test.go
- pkg/sys/it/impl_n10n_test.go
- pkg/sys/it/impl_qpv2_test.go
- pkg/sys/it/impl_signupin_test.go
- pkg/sys/it/impl_sqlquery_test.go
- pkg/sys/it/impl_test.go
- pkg/sys/it/impl_uniques_test.go
- pkg/sys/it/impl_verifier_test.go
- pkg/sys/it/impl_vsqlupdate_test.go
- pkg/vit/impl.go
- pkg/vit/impl_reqopts.go
Resolves #4027 abstractions leak: high-level `sys.Error` is checked by low-level `IHTTPClient`
> abstractions leak: high-level `sys.Error` is checked by low-level `IHTTPClient`

- pkg/coreutils/types.go
- pkg/router/impl_test.go
Resolves #4074 `FuncResponse.UnmarshalJSON()`: eliminate `HTTPResponse` field check
> `FuncResponse.UnmarshalJSON()`: eliminate `HTTPResponse` field check

- pkg/goutils/testingu/clitest.go
- pkg/goutils/testingu/clitest_test.go
Resolves #4150 refactor `Tester` interface in `goutils/testingu`
> refactor `Tester` interface in `goutils/testingu`

- pkg/router/impl_blob.go
- pkg/router/utils.go
Resolves #4163 APIv2 n10n: extract cookie->header auth token func to reuse it among blobs and n10n
> APIv2 n10n: extract cookie->header auth token func to reuse it among blobs and n10n
