voedger/voedger

pkg/processors/command/impl.go
pkg/processors/command/types.go
pkg/processors/query/impl.go
pkg/state/consts.go
pkg/state/impl_command_processor_state.go
pkg/state/impl_host_state_test.go
pkg/state/impl_plog_storage_test.go
pkg/state/impl_query_processor_state.go
pkg/state/impl_records_storage_test.go
pkg/state/impl_subject_storage.go
pkg/state/impl_subject_storage_test.go
pkg/state/impl_view_records_storage_test.go
pkg/state/impl_wlog_storage_test.go
pkg/state/types.go

https://dev.untill.com/projects/#!640031

state: allow to read token from subject storage

---

go.mod
go.sum
pkg/ctrlloop/README.md
pkg/ctrlloop/consts.go
pkg/ctrlloop/impl.go
pkg/ctrlloop/impl_test.go
pkg/ctrlloop/messages.go
pkg/ctrlloop/provide.go
pkg/ctrlloop/types.go
pkg/ctrlloop/utils.go

Migration ctrlloop

---

pkg/istructsmem/contname-types.go
pkg/istructsmem/internal/qnames/interface.go
pkg/istructsmem/internal/utils/bytes.go
pkg/istructsmem/internal/utils/bytes_test.go
pkg/istructsmem/types_test.go
pkg/schemas/validation.go
pkg/schemas/view-schema-utils.go

45 fix missing copyright message

---

pkg/iauthnzimpl/consts.go
pkg/iauthnzimpl/impl_acl.go

ACLs for Payments Portal
https://dev.untill.com/projects/#!641315

ACLs for Payments Portal

---

.github/workflows/merge.yml
.github/workflows/short-go.yml

Fixes voedger/voedger#62

---

.github/workflows/ci-cmd.yml
.github/workflows/ci-pkg-cmd.yml
.github/workflows/merge.yml

Resolves voedger/voedger#73

---

go.mod
go.sum
pkg/iextenginewazero/impl.go
pkg/iextenginewazero/impl_test.go

Resolves voedger/voedger#48

---

cmd/edger/controllers.go
cmd/edger/controllers_test.go
cmd/edger/main.go
cmd/edger/types.go

added docker controller

---

pkg/ctrlloop/impl_test.go

Resolves voedger/voedger#105

---

pkg/ctrlloop/impl_test.go

105 fix data race in ctrlloop tests

---

pkg/projectors/async.go

Resolves voedger/voedger#109

---

cmd/ctool/scripts/drafts/ctool-scylla-deploy.sh
cmd/ctool/scripts/drafts/ctool-scylla-replace-node.sh
cmd/ctool/scripts/drafts/db-bootstrap-end.sh
cmd/ctool/scripts/drafts/db-bootstrap-prepare.sh
cmd/ctool/scripts/drafts/db-cluster-start.sh
cmd/ctool/scripts/drafts/db-node-prepare.sh
cmd/ctool/scripts/drafts/docker-compose-mon.yml
cmd/ctool/scripts/drafts/docker-compose-se.yml
cmd/ctool/scripts/drafts/docker-install.sh
cmd/ctool/scripts/drafts/mon-node-prepare.sh
cmd/ctool/scripts/drafts/mon-stack-start.sh
cmd/ctool/scripts/drafts/se-cluster-start.sh
cmd/ctool/scripts/drafts/swarm-add-node.sh
cmd/ctool/scripts/drafts/swarm-init.sh
cmd/ctool/scripts/drafts/swarm-rm-node.sh
cmd/ctool/scripts/drafts/swarm-set-label.sh

Add-peer-configuration-to-alertmanager

Add-peer-configuration-to-alertmanager

---

pkg/sys/it/impl_sqlquery_test.go

https://dev.untill.com/projects/#!643218

sys_it: fix test Should_read_all_events

---

.github/workflows/integration-test.yml
cmd/ctool/scripts/drafts/mon-node-prepare.sh
cmd/ctool/scripts/terraform/scylla_cluster.tf

Add smoke test for monitor stack

Add smoke test for monitor stack

---

pkg/processors/query/filter-and-impl.go
pkg/processors/query/filter-equals-impl.go
pkg/processors/query/filter-equals-impl_test.go
pkg/processors/query/filter-greater-impl.go
pkg/processors/query/filter-greater-impl_test.go
pkg/processors/query/filter-less-impl.go
pkg/processors/query/filter-less-impl_test.go
pkg/processors/query/filter-not-equals-impl.go
pkg/processors/query/filter-not-equals-impl_test.go
pkg/processors/query/filter-or-impl.go
pkg/processors/query/impl.go
pkg/processors/query/impl_test.go
pkg/processors/query/operator-enrichment-impl.go
pkg/processors/query/operator-enrichment-impl_test.go
pkg/processors/query/operator-filter-impl.go
pkg/processors/query/operator-result-fields-impl.go
pkg/processors/query/operator-result-fields-impl_test.go
pkg/processors/query/query-params-impl.go
pkg/processors/query/types.go
pkg/sys/sqlquery/impl_records.go
pkg/sys/sqlquery/impl_viewrecords.go
pkg/utils/objectreader.go
pkg/utils/objectreader_test.go

Resolves voedger/voedger/issues/71

Get rid of coreutils.FieldsDef

---

pkg/parser/impl.go

Fixes voedger/voedger#150

---

cmd/voedger/wire.go

Fix voedger cmd runner (#178)

---

cmd/edger/main.go
cmd/edger/main_test.go

181 skip testexecrootcmd test if short tests are running

---

cmd/ctool/cluster.go
cmd/ctool/cluster_test.go
cmd/ctool/errors.go
cmd/ctool/repeat.go
cmd/ctool/replace.go
cmd/ctool/scripts.go
cmd/ctool/scripts/drafts/docker-compose-prepare.sh
cmd/ctool/scripts/drafts/swarm-get-manager-token.sh
cmd/ctool/se.go
cmd/ctool/utils.go

Resolves voedger/voedger#155

---

cmd/ctool/scripts/drafts/docker-compose-mon.yml
cmd/ctool/scripts/drafts/docker-compose-se.yml
cmd/ctool/scripts/drafts/grafana/grafana.ini
cmd/ctool/scripts/drafts/grafana/provisioning/dashboards/swarmprom-nodes-dash.json
cmd/ctool/scripts/drafts/grafana/provisioning/dashboards/swarmprom-prometheus-dash.json
cmd/ctool/scripts/drafts/grafana/provisioning/dashboards/swarmprom-services-dash.json
cmd/ctool/scripts/drafts/grafana/provisioning/dashboards/swarmprom_dashboards.yml
cmd/ctool/scripts/drafts/grafana/provisioning/datasources/datasource.yml
cmd/ctool/scripts/drafts/mon-node-prepare.sh
cmd/ctool/scripts/drafts/prometheus/prometheus.yml

Fixes voedger/voedger#158

---

pkg/parser/const.go
pkg/parser/errors.go
pkg/parser/example_app/example.sql
pkg/parser/impl.go
pkg/parser/impl_test.go
pkg/parser/system_pkg/system.sql
pkg/parser/types.go
pkg/parser/utils.go

Resolves voedger/voedger#220

---

pkg/parser/impl_test.go
pkg/parser/utils.go

Resolves #238

---

pkg/sys/authnz/signupin/consts.go
pkg/sys/authnz/signupin/impl_changepassword.go
pkg/sys/authnz/signupin/impl_issueprincipaltoken.go
pkg/sys/authnz/signupin/utils.go
pkg/sys/it/impl_signupin_test.go

240 incorrect login or password

---

pkg/parser/const.go
pkg/parser/errors.go
pkg/parser/impl.go
pkg/parser/impl_test.go

https://github.com/voedger/voedger/issues/236

parser: semantic analysis for references

---

pkg/in10nmem/impl_test.go
pkg/in10nmem/inv/main.go
pkg/in10nmem/provide.go
pkg/processors/command/impl_test.go
pkg/projectors/async_test.go
pkg/vvm/wire_gen.go

in10nmem cleanup

---

.github/workflows/integration-test.yml
cmd/ctool/scripts/terraform/scylla_cluster.tf

Fixes voedger/voedger#156

---

pkg/parser/impl_test.go
pkg/parser/utils.go

https://github.com/voedger/voedger/issues/259

parser: invalid memory address or nil pointer dereference

---

pkg/istructsmem/utils.go
pkg/sys/it/impl_cud_test.go
pkg/vit/shared_cfgs.go

172 validation reference targets

---

pkg/projectors/async.go

Resolves voedger/voedger#303

---

pkg/projectors/async.go
pkg/projectors/async_test.go
pkg/projectors/consts.go
pkg/projectors/interface.go

Resolves voedger/voedger#306

---

pkg/projectors/async.go
pkg/projectors/async_test.go

Resolves voedger/voedger#310

---

.github/workflows/integration-test.yml
cmd/ctool/scripts/terraform/scylla_cluster.tf

Fixes voedger/voedger#142

---

pkg/istoragecache/impl.go
pkg/istoragecache/impl_benchmark_test.go
pkg/metrics/impl.go
pkg/metrics/interface.go

Resolves voedger/voedger#323

---

pkg/istoragecache/impl.go
pkg/metrics/impl.go
pkg/metrics/interface.go
pkg/metrics/types.go

Resolves voedger/voedger#326

---

pkg/istoragecache/consts.go
pkg/istoragecache/impl.go
pkg/istoragecache/impl_benchmark_test.go
pkg/istoragecache/impl_test.go

Resolves voedger/voedger#322

---

pkg/pipeline/async.go
pkg/pipeline/wired-operator.go

Resolves voedger/voedger#342

---

pkg/state/types.go
pkg/state/types_test.go

https://github.com/voedger/voedger/issues/363

state: log wLogStorage key and pLogStorage key in more clear way

---

pkg/parser/const.go
pkg/parser/utils.go

Resolves voedger/voedger#237

---

pkg/parser/example_app/pmain/package.sql
pkg/parser/types.go

Resolves voedger/voedger#377

---

pkg/parser/example_app/pmain/package.sql
pkg/parser/impl.go
pkg/parser/impl_test.go
pkg/parser/utils.go

Resolves voedger/voedger#375

---

go.mod

fix go.mod, butebufferpool

---

.github/workflows/integration-test.yml

Fixes voedger/voedger#206

---

cmd/ctool/cluster.go
cmd/ctool/consts.go
cmd/ctool/main.go
cmd/ctool/scripts/drafts/host-validate.sh
cmd/ctool/se.go

Resolves voedger/voedger#370

---

pkg/iauthnzimpl/consts.go
pkg/iauthnzimpl/impl_acl.go

Resolves voedger/voedger#430

---

pkg/sys/authnz/signupin/consts.go
pkg/sys/authnz/signupin/impl_resetpassword.go
pkg/sys/it/impl_verifier_test.go
pkg/sys/verifier/consts.go
pkg/sys/verifier/impl.go
pkg/sys/verifier/l10n.go
pkg/utils/l10n.go

203 verification email l10n localization

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go

Resolves voedger/voedger#446

---

pkg/sys/authnz/signupin/impl_resetpassword.go
pkg/sys/it/impl_verifier_test.go
pkg/sys/verifier/consts.go

444 verification email l10n localization amendments

---

pkg/pipeline/async-pipeline-impl_test.go
pkg/pipeline/errors.go
pkg/pipeline/impl_test.go
pkg/pipeline/sync-pipeline-impl_test.go
pkg/pipeline/wired-operator.go
pkg/pipeline/wired-operator_test.go
pkg/projectors/async_test.go
pkg/projectors/impl_test.go

449 improve pipeline errors handling

---

pkg/pipeline/async-pipeline-impl_test.go
pkg/pipeline/impl_test.go
pkg/pipeline/sync-pipeline-impl_test.go
pkg/pipeline/sync.go
pkg/pipeline/wired-operator_test.go
pkg/utils/syserror.go

457 pipeline errors handling improvements amendments

---

pkg/parser/const.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/utils.go

Resolves voedger/voedger#483

---

pkg/parser/impl.go
pkg/parser/impl_analyse.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go

Resolves voedger/voedger#484

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go
pkg/parser/utils.go

Resolves voedger/voedger#489

---

pkg/istructs/consts.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/utils.go

Resolves voedger/voedger#479

---

pkg/in10nmem/example_test.go
pkg/in10nmem/impl_test.go

in10nmem: example

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go

Resolves voedger/voedger#465

---

pkg/sys/collection/provide.go

register ap.sys.ProjectorCollection

---

LICENSE
pkg/in10nmem/consts.go
pkg/in10nmem/errors.go
pkg/in10nmem/example_test.go
pkg/in10nmem/impl.go
pkg/in10nmem/impl_test.go
pkg/in10nmem/provide.go
pkg/in10nmem/types.go

MIT license

---

pkg/utils/l10n.go

506 fix error suppression in coreutilsgetcatalogfromtranslations

---

pkg/sys/it/impl_verifier_test.go
pkg/sys/verifier/consts.go
pkg/sys/verifier/impl.go
pkg/sys/verifier/l10n.go

505 use provided translations of the email text

---

pkg/sys/verifier/impl.go

462 localize the email subject

---

pkg/parser/impl.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go
pkg/parser/utils.go

Resolves voedger/voedger#499

---

pkg/in10nmem/impl.go

Resolves voedger/voedger#530

---

pkg/vvm/consts.go
pkg/vvm/provide.go

Resolves voedger/voedger#532

---

pkg/vvm/wire_gen.go

Resolves #538 performance: wire provideAsyncActualizersFactory

Resolves issue performance: wire provideAsyncActualizersFactory

---

pkg/parser/sql_example_app/pmain/package.sql

Resolves #552 Parser: better comments in example app

Resolves issue Parser: better comments in example app

---

pkg/istructsmem/validation-fieldValidator.go
pkg/istructsmem/validation.go

#548 istructsmem: avoid escapes to heap in validators closures

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_test.go

Resolves #550 SQL: Abstract Workspaces

Resolves issue SQL: Abstract Workspaces

---

pkg/parser/const.go
pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/sql_example_app/untill/package.sql
pkg/parser/sql_example_syspkg/system.sql
pkg/parser/types.go
pkg/parser/utils.go

Resolves #456 SQL workspaces: definition, inheritance and using

Resolves issue SQL workspaces: definition, inheritance and using

---

pkg/parser/impl.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go

Resolves #467 SQL: WS Descriptor names

Resolves issue SQL: WS Descriptor names

---

pkg/projectors/async.go

https://github.com/voedger/voedger/issues/561

projectors: async projector logger improvement

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/sql_example_syspkg/system.sql
pkg/parser/utils.go

Resolves #574 SQL: workspaces improvements

Resolves issue 'SQL: workspaces improvements'

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_test.go

Resolves #564 SQL: stack overflow on `TABLE computers INHERITS computers`

Resolves issue 'SQL: stack overflow on `TABLE computers INHERITS computers`'

---

pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/utils.go

Resolves #566 SQL: wrong `IRefField.Refs()` result on ref field

Resolves issue 'SQL: wrong `IRefField.Refs()` result on ref field'

---

pkg/parser/sql_example_app/airsbp/package.sql
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/sql_example_app/untill/package.sql
pkg/parser/sql_example_app/vrestaurant/package.sql

Resolves #579 add copyrights to example SQLs

Resolves issue 'add copyrights to example SQLs'

---

pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go

Resolves #582 SQL: comments for table fields

Resolves issue 'SQL: comments for table fields'

---

pkg/iauthnzimpl/consts.go
pkg/iauthnzimpl/impl_acl.go

https://dev.untill.com/projects/#!650998

iauthnzimpl: modify ACL

---

pkg/sys/verifier/l10n.go

586 sys verifier l10n issue

---

pkg/sys/verifier/provide.go

https://dev.untill.com/projects/#!653396

verifier: make projector sys.SendEmailVerificationCode non buffered

---

pkg/parser/const.go
pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/sql_example_app/vrestaurant/package.sql
pkg/parser/types.go
pkg/parser/utils.go

Resolves #522 SQL: datatype varchar

Resolves issue 'SQL: datatype varchar'

---

pkg/parser/impl_build.go
pkg/parser/sql_example_app/pmain/package.sql

Resolves #598 Parser: Verifiable string fields

Resolves issue 'Parser: Verifiable string fields'

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/sql_example_app/vrestaurant/package.sql
pkg/parser/types.go

Resolves #612 Postgress-like VQL syntax for projectors

Resolves issue 'Postgress-like VQL syntax for projectors'

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_test.go

Resolves #616 parser: semantic analysis for views

Resolves issue 'parser: semantic analysis for views'

---

design/schemas/air.sql
design/schemas/progress/air.sql
design/schemas/progress/air2-before-meeting-20032023.sql
design/schemas/progress/air3-after-meeting-20032023.sql
design/workspaces/README.md
design/workspaces/create-workspace-v2.md
pkg/iauthnzimpl/consts.go
pkg/sys/authnz/workspace/impl.go

This reverts commit 53ac5e1e3b11c2a691bcb46ed15b7a452f0a38f4.

Revert "Rename Air Workspaces (#629)"

---

pkg/state/consts.go
pkg/state/impl_command_processor_state.go
pkg/state/impl_principal_token_storage.go
pkg/state/impl_principal_token_storage_test.go
pkg/state/impl_query_processor_state.go
pkg/state/types.go

601 implement principal token storage

---

pkg/iextengine/interface.go
pkg/iextenginewazero/errors.go
pkg/iextenginewazero/impl.go
pkg/iextenginewazero/impl_benchmark_test.go
pkg/iextenginewazero/impl_test.go

Resolves #644 iextengine: updates

Resolves issue 'iextengine: updates'

---

pkg/parser/impl.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/sql_example_app/vrestaurant/package.sql
pkg/parser/utils.go

Resolves #701 vSQL: the scope of statements

Resolves issue vSQL: the scope of statements

---

pkg/parser/impl_test.go
pkg/parser/utils.go

Resolves issue #704 vSQL scope: ref fields scope incorrect

Resolves issue #704 vSQL scope: ref fields scope incorrect

---

pkg/parser/impl_test.go
pkg/parser/utils.go

Resolves #703 ALTER WORKSPACE is always possible in the workspace package

#703 ALTER WORKSPACE is always possible in the workspace package

---

pkg/istructsmem/idgenerator.go
pkg/istructsmem/idgenerator_test.go

Resolves #718 syncid is in the past

#718 syncid is in the past

---

pkg/istructs/consts.go
pkg/istructsmem/idgenerator.go

Resolves #720 make a const for the minimum allowed RecordID

#720 make a const for the minimum allowed RecordID

---

pkg/parser/impl_build.go

Resolves #724 various tests fails sometimes due of parser error

Resolves issue 'various tests fails sometimes due of parser error'

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/sql_example_app/vrestaurant/package.sql
pkg/parser/types.go

Resolves #432 parser: projector state/intents syntax improvement

Resolves issue 'parser: projector state/intents syntax improvement'

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/utils.go

Resolves #743 Parser: analyse all views are generated by sole projector

#743 Parser: analyse all views are generated by sole projector

---

pkg/router/consts.go
pkg/router/impl_sections.go
pkg/router/impl_test.go
pkg/router/utils.go

Resolves #694 data race in router tests

#694 data race in router tests

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/types.go

Resolves #768 vSQL: support multiples ON in projectors

#768 vSQL: support multiples ON in projectors

---

pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/types.go
pkg/parser/utils.go

Resolves #733 SQL: support USE all tables from package

#733 SQL: support USE all tables from package

---

pkg/parser/const.go
pkg/parser/errors.go
pkg/parser/example_exported_apps/apps.yaml
pkg/parser/example_exported_apps/pkg/github.com/company1/repo/folder1/file.sql
pkg/parser/example_exported_apps/pkg/github.com/company1/repo/folder2/file.sql
pkg/parser/example_exported_apps/pkg/github.com/company2/repo/file.sql
pkg/parser/example_exported_apps/pkg/sys/system.sql
pkg/parser/impl.go
pkg/parser/impl_analyse.go
pkg/parser/impl_exported.go
pkg/parser/impl_test.go
pkg/parser/provide.go
pkg/parser/types.go
pkg/parser/utils.go

Resolves #775 parser: load exported schemas

#775 parser: load exported schemas

---

pkg/apps/consts.go
pkg/apps/sys/blobber/provide.go
pkg/apps/sys/registry/provide.go
pkg/apps/sys/router/provide.go
pkg/apps/types.go
pkg/apps/utils.go
pkg/parser/utils.go
pkg/sys/it/bug_test.go
pkg/sys/it/impl_test.go
pkg/sys/provide.go
pkg/vit/shared_cfgs.go
pkg/vvm/impl_builder.go
pkg/vvm/utils.go

783 make sql file be registered in an extension point instead of fileschemaasts

---

pkg/appdef/consts-restrictions.go

Resolves #809 enlarge field max len to 32768 bytes

#809 enlarge field max len to 32768 bytes

---

pkg/parser/impl_analyse.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go
pkg/parser/utils.go

Resolves #752 sql: projector on any

#752 sql: projector on any

---

pkg/istructsmem/impl.go
pkg/istructsmem/types.go
pkg/registry/utils.go

Resolves #816 investigate "`sys.Login` not found" error 3

#816 investigate "`sys.Login` not found" error 3

---

pkg/appdef/appdef.go
pkg/istructsmem/impl.go
pkg/istructsmem/internal/qnames/impl.go
pkg/istructsmem/types.go
pkg/registry/impl_issueprincipaltoken.go
pkg/registry/utils.go

Resolves #818 remove debug logs

#818 remove debug logs

---

pkg/vit/impl.go
pkg/vvm/impl_cfg.go
pkg/vvm/provide.go
pkg/vvm/test_utils.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #825 allow secrets reader bypass

#825 allow secrets reader bypass

---

pkg/vit/impl.go
pkg/vvm/impl_cfg.go

Resolves #827 use TestSecretsReader in tests

#827 use TestSecretsReader in tests

---

pkg/appdefcompat/const.go

830 appdefcompat use instead of

---

pkg/parser/utils.go

800 delete parserloadexportedapps related artifacts

---

pkg/sys/invite/impl_initiateinvitationbyemail.go
pkg/sys/invite/impl_initiateupdateinviteroles.go

Resolves #840 enlarge text fields

#840 enlarge text fields

---

cmd/ctool/consts.go
cmd/ctool/scripts/drafts/ctool-scylla-replace-node.sh
cmd/ctool/scripts/drafts/ctool-set-hostnames.sh
cmd/ctool/scripts/drafts/db-bootstrap-end.sh
cmd/ctool/scripts/drafts/db-bootstrap-prepare.sh
cmd/ctool/scripts/drafts/db-cluster-start.sh
cmd/ctool/scripts/drafts/db-node-prepare.sh
cmd/ctool/scripts/drafts/db-stack-update.sh
cmd/ctool/scripts/drafts/docker-compose-prepare.sh
cmd/ctool/scripts/drafts/docker-install.sh
cmd/ctool/scripts/drafts/host-validate.sh
cmd/ctool/scripts/drafts/mon-node-prepare.sh
cmd/ctool/scripts/drafts/mon-stack-start.sh
cmd/ctool/scripts/drafts/node-set-hostname.sh
cmd/ctool/scripts/drafts/node-update-hosts.sh
cmd/ctool/scripts/drafts/prometheus-tsdb-copy.sh
cmd/ctool/scripts/drafts/se-cluster-start.sh
cmd/ctool/scripts/drafts/swarm-add-node.sh
cmd/ctool/scripts/drafts/swarm-get-manager-token.sh
cmd/ctool/scripts/drafts/swarm-init.sh
cmd/ctool/scripts/drafts/swarm-rm-node.sh
cmd/ctool/scripts/drafts/swarm-set-label.sh
cmd/ctool/scripts/drafts/utils.sh
cmd/ctool/se.go

ssh optionms now use as separate args

863 ctool air live cluster ssh options

---

pkg/sys/uniques/impl.go

Resolves #873 translate to English comments in `uniques` implementation

#873 translate to English comments in `uniques` implementation

---

pkg/apps/sys/blobberapp/provide.go
pkg/apps/sys/registryapp/provide.go
pkg/apps/sys/routerapp/provide.go
pkg/sys/builtin/impl_refintegrity.go
pkg/sys/builtin/provide.go
pkg/sys/it/bug_test.go
pkg/sys/it/impl_test.go
pkg/sys/provide.go
pkg/sys/uniques/impl.go
pkg/vit/impl_vitcfg.go
pkg/vit/shared_cfgs.go

Resolves #879 Voedger: eliminate --rebuild-registry feature after #663 is merged into Release and RC

#879 Voedger: eliminate --rebuild-registry feature after #663 is merged into Release and RC

---

pkg/processors/command/impl.go

Resolves #881 add logging the issued ids

#881 add logging the issued ids

---

pkg/istructsmem/idgenerator.go
pkg/processors/command/impl.go

Resolves #886 ID generator could issue an already issued ID

#886 ID generator could issue an already issued ID

---

cmd/ctool/scripts/drafts/docker-compose-mon.yml
cmd/ctool/scripts/drafts/docker-compose-se.yml
cmd/ctool/scripts/drafts/docker-compose-template.yml
cmd/ctool/scripts/drafts/docker-install.sh
cmd/ctool/scripts/drafts/prometheus-tsdb-copy.sh

Add use external network in swarm mode

889 ctool scylla cluster use network in host mode

---

.github/workflows/cd-voedger.yml
cmd/ctool/go.mod
cmd/edger/go.mod
cmd/voedger/go.mod
go.mod
go.work

Resolves #904 use golang 1.21.4 in github action

#904 use golang 1.21.4 in github action

---

pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/sql_example_app/vrestaurant/package.sql

Resolves #839 parser/Test_BasicUsage() is failed on build `IAppDef`

#839 parser/Test_BasicUsage() is failed on build `IAppDef`

---

pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/types.go

Resolves #915 parser: support collections in type

#915 parser: support collections in type

---

pkg/sys/sys.sql

Resolves #948 restore `c.sys.InitiateDeactivateWorkspace` in sys.sql

#948 restore `c.sys.InitiateDeactivateWorkspace` in sys.sql

---

pkg/appdefcompat/sql/new.sql
pkg/appdefcompat/sql/old.sql
pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go
pkg/sys/sys.sql

Resolves #954 sql: add `AFTER EXECUTE` for commands

#954 sql: add `AFTER EXECUTE` for commands

---

pkg/utils/syserror.go
pkg/utils/syserror_test.go

Resolves #960 fix sys.Error.Error()

#960 fix sys.Error.Error()

---

pkg/sys/sys.sql

Resolves #924 indent by tabs `pkg/sys/sys.sql`

#924 indent by tabs `pkg/sys/sys.sql`

---

go.mod
go.sum
pkg/vvm/impl_builder.go
pkg/vvm/provide.go
pkg/vvm/utils.go
pkg/vvm/wire_gen.go

Resolves #852 panic -> return error in `VVMAppsBuilder.Build()`

#852 panic -> return error in `VVMAppsBuilder.Build()`

---

pkg/vvm/impl_builder.go

Resolves #781 wrong error messages if func name in sql and resources differs

#781 wrong error messages if func name in sql and resources differs

---

pkg/router/impl_reverseproxy.go
pkg/vit/impl.go
pkg/vit/shared_cfgs.go

Resolves #966 fix reverseproxy tests

#966 fix reverseproxy tests

---

pkg/router/impl_reverseproxy.go
pkg/sys/it/reverseproxy_test.go

Resolves #969 improve reverseproxy logging

#969 improve reverseproxy logging

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go
pkg/parser/utils.go
pkg/registry/provide.go
pkg/sys/invite/provide.go
pkg/sys/journal/provide.go
pkg/sys/verifier/provide.go
pkg/sys/workspace/impl_deactivate.go
pkg/sys/workspace/provide.go

Resolves #972 parser: register projectors in appdef

#972 parser: register projectors in appdef

---

pkg/istructs/consts.go
pkg/processors/command/impl.go
pkg/processors/command/impl_test.go
pkg/processors/consts.go
pkg/processors/provide.go
pkg/processors/query/impl.go
pkg/processors/query/impl_test.go
pkg/processors/query/operator-raw-result.go
pkg/sys/provide.go

Resolves #977 type raw: QP, CP: use raw type

#977 type raw: QP, CP: use raw type

---

pkg/processors/provide.go

Resolves #979 set MaxRawFieldLength as len of `RawObject`

#979 set MaxRawFieldLength as len of `RawObject`

---

pkg/ihttp/interface.go
pkg/ihttpimpl/consts.go
pkg/ihttpimpl/impl.go
pkg/ihttpimpl/impl_test.go
pkg/ihttpimpl/provide.go

874 ihttp add reverse proxy controlling methods addroutesrewriteproxy

---

pkg/ihttpimpl/impl.go
pkg/ihttpimpl/impl_test.go

996 fix linters after 874

---

pkg/processors/command/impl_test.go
pkg/processors/query/impl.go

Resolves #1003 fix bytes field type in go code

#1003 fix bytes field type in go code

---

pkg/parser/sql_example_syspkg/system.sql

Resolves #947 type raw: voedger: sys.sql: sys.Raw, comments

#947 type raw: voedger: sys.sql: sys.Raw, comments

---

pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/types.go

Resolves #942 parser: rename in types Arg -> Param

#942 parser: rename in types Arg -> Param

---

pkg/parser/impl_test.go
pkg/parser/types.go

Resolves #998 parser: make ability to make empty TYPE

#998 parser: make ability to make empty TYPE

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go

Resolves #994 parser: Projector can be triggered by command argument type

#994 parser: Projector can be triggered by command argument type

---

pkg/sys/sys.sql

Resolves #1021 fix ApplyUniques and RecordRegistryProjector declarations

#1021 fix ApplyUniques and RecordRegistryProjector declarations

---

pkg/parser/impl.go
pkg/parser/impl_analyse.go
pkg/parser/impl_test.go

Resolves #1023 parser: deny ORecord as projector argument

#1023 parser: deny ORecord as projector argument

---

pkg/parser/impl_build.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go

Resolves #1025 parser: projector: INCLUDING ERRORS

#1025 parser: projector: INCLUDING ERRORS

---

pkg/registry/impl_invokecreateworkspaceid.go
pkg/sys/workspace/impl.go

Resolves #1033 sys/workspace amendments

#1033 sys/workspace amendments

---

pkg/utils/mock.go

https://dev.untill.com/projects/#!668331

coreutils: generate mocks

---

pkg/sys/it/impl_deactivateworkspace_test.go
pkg/sys/sys.sql

Resolves #1017 TestBasicUsage_InitiateDeactivateWorkspace is not failed on async projector error

#1017 TestBasicUsage_InitiateDeactivateWorkspace is not failed on async projector error

---

pkg/processors/query/impl.go

Resolves #1046 fix QueryArgs building in Query processor

#1046 fix QueryArgs building in Query processor

---

pkg/utils/consts.go
pkg/utils/email.go

https://dev.untill.com/projects/#!668750

coreutils: export constant

---

pkg/sys/sys.sql

Resolves #1050 use `INCLUDING ERRORS` in sql

#1050 use `INCLUDING ERRORS` in sql

---

pkg/istructs/events-types.go
pkg/istructsmem/event-types.go
pkg/istructsmem/event-types_test.go
pkg/istructsmem/test_test.go
pkg/processors/command/impl.go
pkg/projectors/impl_helpers_test.go
pkg/registry/impl_createlogin.go
pkg/registry/impl_invokecreateworkspaceid.go
pkg/state/impl_plog_storage.go
pkg/state/impl_test.go
pkg/state/impl_wlog_storage.go
pkg/state/impl_wlog_storage_test.go
pkg/state/types.go
pkg/sys/builtin/impl_refintegrity.go
pkg/sys/collection/collection.go
pkg/sys/invite/impl_applyleaveworkspace.go
pkg/sys/invite/impl_inviteindexprojector.go
pkg/sys/invite/impl_joinedworkspaceindexprojector.go
pkg/sys/invite/impl_subject.go
pkg/sys/journal/types.go
pkg/sys/sqlquery/impl_plog.go
pkg/sys/sqlquery/impl_wlog.go
pkg/sys/uniques/impl.go
pkg/sys/workspace/impl.go
pkg/sys/workspace/impl_childworkspace.go
pkg/utils/mock.go
pkg/vit/mock/impl.go

Resolves #1052 eliminate error return in `IAbstractEvent.CUDs`

#1052 eliminate error return in `IAbstractEvent.CUDs`

---

pkg/istructs/consts.go
pkg/istructs/projectors-types.go
pkg/istructsmem/idgenerator_test.go
pkg/istructsmem/impl.go
pkg/parser/impl_test.go
pkg/projectors/async.go
pkg/projectors/async_test.go
pkg/projectors/consts.go
pkg/projectors/impl.go
pkg/projectors/impl_helpers_test.go
pkg/projectors/impl_test.go
pkg/projectors/types.go
pkg/projectors/types_test.go
pkg/sys/collection/collection_test.go
pkg/sys/invite/impl_applycancelacceptedinvite.go
pkg/sys/invite/impl_applyinvitationprojector.go
pkg/sys/invite/impl_applyjoinworkspace.go
pkg/sys/invite/impl_applyleaveworkspace.go
pkg/sys/invite/impl_applyupdateinviteroles.go
pkg/sys/invite/impl_inviteindexprojector.go
pkg/sys/invite/impl_joinedworkspaceindexprojector.go
pkg/sys/it/impl_signupin_test.go
pkg/sys/journal/provide.go
pkg/sys/sys.sql
pkg/sys/verifier/provide.go
pkg/sys/workspace/impl_deactivate.go
pkg/sys/workspace/provide.go
pkg/utils/test_utils.go

Resolves #1084 return back loading projectors definitions from AppDef

#1084 return back loading projectors definitions from AppDef

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_test.go

Resolves #1073 Do not build appdef (all errors should be shown by parsing, e.g. int567)

#1073 Do not build appdef (all errors should be shown by parsing, e.g. int567)

---

cmd/ctool/cluster.go
cmd/ctool/cluster_test.go
cmd/ctool/scripts.go

Resolves voedger/voedger#1088

---

pkg/vvm/consts.go

Resolves #1099 n10n: set max allowed subscriptions per subject to 100

#1099 n10n: set max allowed subscriptions per subject to 100

---

cmd/vpm/compile.go
cmd/vpm/const.go
cmd/vpm/internal/dm/const.go
cmd/vpm/internal/dm/impl_golang.go
cmd/vpm/internal/dm/interface.go
cmd/vpm/internal/dm/provide.go
cmd/vpm/main.go
cmd/vpm/main_test.go
cmd/vpm/test/myapp/myapp.sql
cmd/vpm/test/myapp/mypkg1/schema1.sql
cmd/vpm/test/myapp/mypkg2/schema2.sql
cmd/vpm/test/myapp/mypkg3/schema3.sql
cmd/vpm/test/myapperr/mypkg1/schema1.sql
cmd/vpm/test/myapperr/mypkg2/schema2.sql

1101 refactor vpm compile

---

pkg/vvm/consts.go

Creating articles.
https://dev.untill.com/projects/#!669630

n10n: Creating articles. (channels per subject 10->50)

---

pkg/istructs/utils_test.go
pkg/istructs/validators-types.go
pkg/utils/validators.go
pkg/utils/validators_test.go

Resolves #1113 implement MatchQName() util func for CUD validators

#1113 implement MatchQName() util func for CUD validators

---

cmd/vpm/baseline.go
cmd/vpm/compile.go
cmd/vpm/const.go
cmd/vpm/internal/dm/impl_golang.go
cmd/vpm/internal/dm/interface.go
cmd/vpm/internal/dm/provide.go
cmd/vpm/main.go
cmd/vpm/main_test.go
cmd/vpm/types.go
pkg/parser/provide.go

1057 vpm baseline single package and application

---

.github/workflows/integration-test.yml

Update app-node-02 -> app-node-2

Update intergation test

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go

Resolves #1072 eliminate panic raising in parser

#1072 eliminate panic raising in parser

---

pkg/iextengine/impl.go
pkg/iextengine/impl_test.go
pkg/iextengine/interface.go
pkg/iextengine/provide.go

Resolves #1129 iextengine.IExtensionEngineFactories in iextengine

#1129 iextengine.IExtensionEngineFactories in iextengine

---

pkg/apps/types.go
pkg/vvm/impl.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #1133 Implement and wire apppartsctl (service)

#1133 Implement and wire apppartsctl (service)

---

cmd/vpm/baseline.go
cmd/vpm/compile.go
cmd/vpm/main_test.go

Resolves #1136 baseline tests are not working on Windows

#1136 baseline tests are not working on Windows

---

cmd/vpm/baseline.go
cmd/vpm/compat.go
cmd/vpm/compile.go
cmd/vpm/internal/dm/impl_golang.go
cmd/vpm/main.go
cmd/vpm/main_test.go
cmd/vpm/test/myapp_incompatible/ignores.yml
cmd/vpm/test/myapp_incompatible/myapp.sql
cmd/vpm/test/myapp_incompatible/mypkg1/schema1.sql
cmd/vpm/test/myapp_incompatible/mypkg2/schema2.sql
cmd/vpm/test/myapp_incompatible/mypkg3/schema3.sql
cmd/vpm/test/myapp_incompatible/test.go.mod
cmd/vpm/types.go

1103 vpm compat single package and application

---

cmd/voedger/go.mod
cmd/voedger/go.sum
cmd/vpm/compat.go
cmd/vpm/main_test.go
go.mod

1140 get rid of different yaml engines usage

---

pkg/router/impl_http.go

Resolves #1147 log request url on each request

#1147 log request url on each request

---

cmd/vpm/baseline.go
cmd/vpm/compat.go
cmd/vpm/compile.go
cmd/vpm/const.go
cmd/vpm/main_test.go
cmd/vpm/types.go
pkg/appdefcompat/impl.go

1145 make vpm commands work with windows slashes in paths

---

cmd/vpm/compat.go

1151 testcompaterrors is failed on windows

---

cmd/vpm/compat.go
cmd/vpm/main_test.go

1158 vpm compat demand target dir be actually baseline dir not any

---

cmd/vpm/baseline.go

1172 baselinejson hash is not detected is c is used

---

cmd/vpm/baseline.go
cmd/vpm/const.go
cmd/vpm/main_test.go

1176 vpm baseline check that target folder does not exist

---

pkg/registry/appws.sql
pkg/registry/consts.go
pkg/sys/sys.sql

Resolves #627 voedger: describe system workspaces

#627 voedger: describe system workspaces

---

pkg/sys/invite/impl_applycancelacceptedinvite.go
pkg/sys/invite/impl_applyinvitationprojector.go
pkg/sys/invite/impl_applyjoinworkspace.go
pkg/sys/invite/impl_applyleaveworkspace.go
pkg/sys/invite/impl_applyupdateinviteroles.go

Resolves #1170 discard response on federation request where the response in not used

#1170 discard response on federation request where the response in not used

---

cmd/vpm/compile.go

1200 voedgerpkgsys vpm compile panics

---

cmd/vpm/compile.go

1202 airs bp3packagesair vpm compile panics

---

pkg/apps/sys/blobberapp/provide.go
pkg/apps/sys/registryapp/provide.go
pkg/apps/sys/routerapp/provide.go
pkg/apps/types.go
pkg/sys/invite/impl_applyinvitationprojector.go
pkg/sys/it/bug_test.go
pkg/sys/it/impl_test.go
pkg/vit/impl_vitcfg.go
pkg/vit/shared_cfgs.go
pkg/vvm/impl_builder.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #1209 Export sql packages the VVM applications are built from

#1209 Export sql packages the VVM applications are built from

---

design/workspaces/invites.md
pkg/sys/invite/impl_applyinvitation.go

Resolves #1211 update Invites doc

#1211 update Invites doc

---

design/workspaces/deactivate-workspace.md
pkg/sys/invite/errors.go
pkg/sys/invite/impl_applyjoinworkspace.go
pkg/sys/invite/impl_cancelsentinvite.go
pkg/sys/invite/impl_initiatecancelacceptedinvite.go
pkg/sys/invite/impl_initiateinvitationbyemail.go
pkg/sys/invite/impl_initiatejoinworkspace.go
pkg/sys/invite/impl_initiateleaveworkspace.go
pkg/sys/invite/impl_initiateupdateinviteroles.go
pkg/sys/invite/utils.go
pkg/sys/it/impl_deactivateworkspace_test.go
pkg/sys/it/impl_invite_test.go
pkg/sys/it/impl_verifier_test.go
pkg/sys/it/test_utils.go
pkg/vit/impl.go
pkg/vit/shared_cfgs.go
pkg/vit/utils.go

Resolves #1105 c.sys.InitiateInvitationByEMail should overwrite roles

#1105 c.sys.InitiateInvitationByEMail should overwrite roles

---

cmd/voedger/server.go
cmd/voedger/wire.go
cmd/voedger/wire_gen.go
pkg/apps/consts.go
pkg/apps/provide.go
pkg/apps/types.go
pkg/ihttp/interface.go
pkg/ihttp/provide.go
pkg/ihttp/types.go
pkg/ihttpctl/provide.go
pkg/ihttpctl/types.go
pkg/ihttpimpl/consts.go
pkg/ihttpimpl/impl.go
pkg/ihttpimpl/impl_test.go
pkg/ihttpimpl/provide.go

1165 implement ctool https

---

pkg/parser/errors.go
pkg/parser/impl.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go

Resolves #1160 parser: `UNIQUE`

#1160 parser: `UNIQUE`

---

cmd/vpm/compat.go
pkg/utils/utils.go

1229 vpm compat at airs bp3 baseline schema panics

---

pkg/parser/impl_build.go

Resolves #1213 func findSchemaByPkg must not return nil in parser

#1213 func findSchemaByPkg must not return nil in parser

---

pkg/sys/it/impl_deactivateworkspace_test.go
pkg/sys/it/impl_invite_test.go
pkg/sys/it/test_utils.go

Resolves #1235 fix invite basic usage test

#1235 fix invite basic usage test

---

cmd/vpm/baseline.go
cmd/vpm/compat.go

1232 fix requires at least 1 args only received 0 error on no args from vpm compat and baseline

---

cmd/voedger/consts.go
cmd/voedger/server.go
cmd/voedger/wire.go
cmd/voedger/wire_gen.go
pkg/apps/consts.go
pkg/apps/provide.go
pkg/ihttp/types.go
pkg/ihttpimpl/impl_test.go

1192 voedger cmd eliminate grafana and prometheus ports wiring 1

---

cmd/voedger/types.go
cmd/voedger/wire.go
cmd/voedger/wire_gen.go
pkg/ihttp/interface.go
pkg/ihttpctl/impl.go
pkg/ihttpctl/provide.go
pkg/ihttpimpl/impl.go
pkg/ihttpimpl/impl_test.go
pkg/ihttpimpl/provide.go

1219 get rid of ihttpprocessorapi interface

---

pkg/utils/mock.go

https://dev.untill.com/projects/#!672995

coreutils: add mock

---

pkg/ihttpimpl/impl.go
pkg/ihttpimpl/impl_test.go

1220 eliminate possible race condition in httpprocessor

---

pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/types.go
pkg/parser/utils.go

Resolves #1256 parser: better error positions

#1256 parser: better error positions

---

pkg/sys/invite/impl_applyjoinworkspace.go

Resolves #1275 wrong skipping condition on `ap.sys.ApplyJoinWorkspace`

#1275 wrong skipping condition on `ap.sys.ApplyJoinWorkspace`

---

cmd/vpm/compile.go
cmd/vpm/internal/dm/impl_golang.go
cmd/vpm/main_test.go

1283 vpm vpm compile c gomod not found

---

cmd/vpm/main.go

1282 vpm consistent naming

---

go.mod
pkg/processors/command/impl_test.go
pkg/router/impl_test.go
pkg/vvm/impl_requesthandler.go
staging/src/github.com/untillpro/ibusmem/impl.go
staging/src/github.com/untillpro/ibusmem/impl_bench_test.go
staging/src/github.com/untillpro/ibusmem/impl_test.go
staging/src/github.com/untillpro/ibusmem/provide.go
staging/src/github.com/untillpro/ibusmem/types.go

Resolves #1290 provide IBus to the bus request handler

#1290 provide IBus to the bus request handler

---

pkg/processors/command/impl.go
pkg/processors/command/impl_test.go
pkg/processors/command/provide.go
pkg/processors/command/types.go
pkg/processors/query/bench_test.go
pkg/processors/query/impl.go
pkg/processors/query/impl_test.go
pkg/processors/query/query-params-impl_test.go
pkg/processors/query/types.go
pkg/router/impl_test.go
pkg/sys/collection/collection_test.go
pkg/utils/http.go
pkg/utils/http_test.go
pkg/vvm/impl_requesthandler.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go
staging/src/github.com/untillpro/airs-ibus/interface.go
staging/src/github.com/untillpro/ibusmem/impl.go
staging/src/github.com/untillpro/ibusmem/impl_bench_test.go
staging/src/github.com/untillpro/ibusmem/impl_test.go
staging/src/github.com/untillpro/ibusmem/provide.go
staging/src/github.com/untillpro/ibusmem/types.go

Resolves #1292 get rid of IBus wiring on processors creation

#1292 get rid of IBus wiring on processors creation

---

cmd/ctool/cluster.go
cmd/ctool/init.go
cmd/ctool/main.go
cmd/ctool/main_test.go

Resolves #1300 ctool: --acme-domains option to the init command

#1300 ctool: --acme-domains option to the init command

---

pkg/sys/it/impl_invite_test.go
pkg/vit/impl.go
pkg/vit/impl_test.go
pkg/vit/impl_vitcfg.go
pkg/vit/shared_cfgs.go
pkg/vit/types.go
pkg/vit/utils.go

Create child workspace
https://dev.untill.com/projects/#!670886

vit: create child workspace

---

cmd/ctool/scripts/drafts/docker-compose-se.yml
cmd/ctool/scripts/terraform/scylla_cluster.tf
cmd/ctool/scripts/terraform/security_group.tf
cmd/ctool/scripts/terraform/variables.tf
cmd/voedger/Dockerfile

Update:
-  voedger Dockerfile
- terraform config 
- SE stack compose templates

1190 integration test including acme and scylla cas3

---

design/api/README.md

Resolves #1318 A&D: errors syntax

#1318 A&D: errors syntax

---

cmd/voedger/wire_gen.go
pkg/apps/sys/registryapp/provide.go
pkg/ihttpctl/provide.go
pkg/ihttpimpl/impl_test.go
pkg/ihttpimpl/provide.go
pkg/istorage/types.go
pkg/istructsmem/resources-types.go
pkg/parser/impl_test.go
pkg/projectors/impl.go
pkg/registry/impl_invokecreateworkspaceid.go
pkg/registry/provide.go
pkg/router/impl_test.go
pkg/router/provide.go
pkg/state/impl_subject_storage.go
pkg/sys/authnz/provide.go
pkg/sys/describe/provide.go
pkg/sys/invite/provide.go
pkg/sys/invite/utils.go
pkg/sys/it/impl_deactivateworkspace_test.go
pkg/sys/it/test_utils.go
pkg/sys/provide.go
pkg/sys/verifier/provide.go
pkg/sys/workspace/impl.go
pkg/sys/workspace/impl_deactivate.go
pkg/vit/utils.go
pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #1353 fix unused args, respect linter

#1353 fix unused args, respect linter

---

pkg/utils/mock.go

Resolves #1357 implement `MockStateKeyBuilder.PutFromJSON()`

#1357 implement `MockStateKeyBuilder.PutFromJSON()`

---

pkg/parser/impl.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/provide.go
pkg/parser/types.go
pkg/parser/utils.go

Resolves #1361 parser: variables

#1361 parser: variables

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/types.go

Resolves #1363 parser: remove support of `WITH RATE...`

#1363 parser: remove support of `WITH RATE...`

---

pkg/parser/sql_example_app/pmain/package.sql

Resolves #1370 parser: improve sql example

#1370 parser: improve sql example

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql

Resolves #1372 parser: better LIMIT semantic analysis

#1372 parser: better LIMIT semantic analysis

---

.golangci.yml
pkg/apps/consts.go
pkg/apps/provide.go
pkg/in10nmem/inv/consts.go
pkg/in10nmem/inv/main.go
pkg/processors/command/impl_test.go
pkg/router/consts.go
pkg/router/impl_n10n.go
pkg/state/types.go
pkg/sys/authnz/consts.go
pkg/sys/sqlquery/impl.go
pkg/sys/workspace/impl.go
pkg/utils/test_utils.go
pkg/vit/consts.go
pkg/vit/shared_cfgs.go
pkg/vit/utils.go
pkg/vvm/consts.go
pkg/vvm/impl_appws.go

1367 linters voedger turn on and respect first 5 linters

---

pkg/sys/it/impl_invite_test.go

Resolves #1376 voedger tests fail on arm64

#1376 voedger tests fail on arm64

---

pkg/vit/impl.go
pkg/vit/impl_vitcfg.go
pkg/vit/types.go

Resolves #1382 implement `VIT.WithInit()` option

#1382 implement `VIT.WithInit()` option

---

pkg/istructs/consts.go
pkg/processors/command/impl_test.go
pkg/sys/it/impl_cud_test.go
pkg/sys/it/impl_invite_test.go
pkg/sys/it/impl_sqlquery_test.go

gaurantee that ID used as an unexisting ID will actually never exist

---

pkg/sys/builtin/consts.go
pkg/sys/builtin/impl_refintegrity.go
pkg/sys/builtin/utils.go

https://dev.untill.com/projects/#!660030

builtin: export fields and function

---

pkg/sys/uniques/impl.go
pkg/vvm/wire_gen.go

Resolves #1408 nil memory dereference on update a record with uniques

#1408 nil memory dereference on update a record with uniques

---

.golangci.yml

1423 linters voedger testifylint exclude indelta requirement

---

pkg/sys/sys.sql

Resolves #1433 make workspace sys.UserProfile alterable to define air.UserProfile there

#1433 make workspace sys.UserProfile alterable to define air.UserProfile there

---

pkg/processors/query/impl.go
pkg/sys/it/race_cud_test.go

Resolves #1440 clarify the error when actual ANY query result type is unknown

#1440 clarify the error when actual ANY query result type is unknown

---

pkg/sys/it/impl_deactivateworkspace_test.go
pkg/sys/it/impl_invite_test.go
pkg/sys/it/impl_verifier_test.go
pkg/sys/it/race_signup_test.go
pkg/vit/utils.go

Resolves #1455 fix non-acomplished actions in Test_Race_SUsignUpIn()

#1455 fix non-acomplished actions in Test_Race_SUsignUpIn()

---

pkg/sys/it/impl_signupin_test.go
pkg/sys/it/test_utils.go

Resolves #1457 VIT: fix additional non-acomplishing actions in tests

#1457 VIT: fix additional non-acomplishing actions in tests

---

pkg/projectors/async.go

Resolves #1466 projectors: do not log error if no error

#1466 projectors: do not log error if no error

---

pkg/sys/smtp/impl.go
pkg/sys/smtp/types.go

Resolves #1477 smtp: add `From` property

#1477 smtp: add `From` property

---

pkg/iextenginewazero/const.go
pkg/iextenginewazero/errors.go
pkg/iextenginewazero/impl.go
pkg/iextenginewazero/impl_benchmark_test.go
pkg/iextenginewazero/impl_helpers_test.go
pkg/iextenginewazero/impl_test.go
pkg/iextenginewazero/provide.go
staging/src/github.com/voedger/exttinygo/README.md
staging/src/github.com/voedger/exttinygo/consts.go
staging/src/github.com/voedger/exttinygo/impl.go
staging/src/github.com/voedger/exttinygo/impl_go.go
staging/src/github.com/voedger/exttinygo/impl_tinygo.go
staging/src/github.com/voedger/exttinygo/intent.go
staging/src/github.com/voedger/exttinygo/interface.go
staging/src/github.com/voedger/exttinygo/key.go
staging/src/github.com/voedger/exttinygo/keybuilder.go
staging/src/github.com/voedger/exttinygo/types.go
staging/src/github.com/voedger/exttinygo/value.go

Resolves #1502 ext packages: refactor package names

#1502 ext packages: refactor package names

---

pkg/appparts/errors.go
pkg/appparts/impl.go
pkg/apps/sys/blobberapp/const.go
pkg/apps/sys/routerapp/const.go
pkg/projectors/async.go
pkg/vit/consts.go
pkg/vit/impl.go

Resolves #1519 async actualizers: wait for app deploy

#1519 async actualizers: wait for app deploy

---

pkg/istorage/provider/impl.go
pkg/istorage/provider/impl_test.go

Resolves #1531 clarify istorage keyspace name generation comments

#1531 clarify istorage keyspace name generation comments

---

pkg/projectors/async.go
pkg/projectors/consts.go

Resolves #1534 async projectors: watch over context on trying to borrow app partition

#1534 async projectors: watch over context on trying to borrow app partition

---

pkg/projectors/async.go

Resolves #1536 async projectors: watch over context on trying to borrow app partition (amend)

#1536 async projectors: watch over context on trying to borrow app partition (amend)

---

cmd/vpm/main_test.go
cmd/vpm/test/myapperr/myapp.sql
cmd/vpm/test/myapperr/mypkg3/schema3.sql
pkg/parser/errors.go
pkg/parser/impl.go
pkg/parser/impl_test.go

1514 vpm compat package local names shall not be changed 1

---

pkg/vit/impl.go
pkg/vvm/impl_cfg.go

Resolves #1461 VIT: use TestSecretsReader by default

#1461 VIT: use TestSecretsReader by default

---

pkg/sys/it/impl_workspace_test.go
pkg/sys/workspace/impl_childworkspace.go
pkg/sys/workspace/provide.go

Resolves #1551 voedger: do not allow to create workspaces with kind that is not a workspace QName

#1551 voedger: do not allow to create workspaces with kind that is not a workspace QName

---

examples/airs-bp/air/extwasm/main_test.go
examples/airs-bp/air/extwasm/orm/package_untill.go

examples: minor

---

pkg/appparts/impl.go

Resolves #1573 appparts: data race

#1573 appparts: data race

---

pkg/projectors/async.go

Resolves #1581 fix "no available engines" on app start

#1581 fix "no available engines" on app start

---

pkg/projectors/async.go

Resolves #1585 fix "nil memory dereference" on app start

#1585 fix "nil memory dereference" on app start

---

pkg/iextenginewazero/errors.go
pkg/iextenginewazero/impl.go

Resolves #1595 iextenginewasm: panic with nil err

#1595 iextenginewasm: panic with nil err

---

pkg/parser/const.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/sql_example_syspkg/system.sql
pkg/parser/types.go
pkg/sys/sys.sql

Resolves #1607 parser: CSingleton / WSingleton

#1607 parser: CSingleton / WSingleton

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/sql_example_app/pmain/package.sql
pkg/parser/types.go

Resolves #1608 parser: STATE and INTENTS for commands and queries

#1608 parser: STATE and INTENTS for commands and queries

---

examples/airs-bp/README.md
examples/airs-bp/air/extwasm/orm/package_air.go
pkg/sys/sys.sql
pkg/vit/schemaTestApp1.sql

Resolves #1628 voedger: Singleton -> CSingleton

#1628 voedger: Singleton -> CSingleton

---

pkg/vvm/impl_requesthandler.go

Resolves #1641 request handling: fix wrong funcs

#1641 request handling: fix wrong funcs

---

pkg/vit/impl.go

Resolves #1635 vit: eliminate manual apps deployment

#1635 vit: eliminate manual apps deployment

---

pkg/processors/command/impl.go

Resolves #1643 CP: consider IWorkspace could be nil on recovery

#1643 CP: consider IWorkspace could be nil on recovery

---

pkg/apps/sys/blobberapp/provide.go
pkg/apps/sys/registryapp/provide.go
pkg/apps/sys/routerapp/provide.go
pkg/apps/utils.go
pkg/iextengine/interface.go
pkg/iextengine/types.go
pkg/iextenginewazero/impl.go
pkg/parser/impl.go
pkg/parser/impl_analyse.go
pkg/parser/interface.go
pkg/parser/provide.go
pkg/parser/types.go
pkg/registry/provide.go
pkg/sys/provide.go
pkg/vit/shared_cfgs.go
pkg/vvm/impl_builder.go

Resolves #1645 iextengine: QualifiedPackageName => Path, PackageName => PackagePath

#1645 iextengine: QualifiedPackageName => Path, PackageName => PackagePath

---

pkg/vvm/impl_requesthandler.go

Resolves #1651 remove temporary fix made by #1588 (return 503 if partitions are not deployed yet)

#1651 remove temporary fix made by #1588 (return 503 if partitions are not deployed yet)

---

pkg/processors/command/impl.go
pkg/processors/command/impl_test.go
pkg/processors/query/impl.go

Resolves #1653 CP, QP: return 503 if the partition is not deployed yet

#1653 CP, QP: return 503 if the partition is not deployed yet

---

pkg/parser/impl_build.go
pkg/parser/impl_test.go

Resolves #1670 parser: build state and intens for commands -> appdef

#1670 parser: build state and intens for commands -> appdef

---

pkg/parser/impl.go
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.sql

Resolves #1484 parser: Identifier requirements

#1484 parser: Identifier requirements

---

pkg/appdefcompat/impl_test.go
pkg/appdefcompat/sql/sys.new.sql
pkg/appdefcompat/sql/sys.old.sql
pkg/parser/errors.go
pkg/parser/impl.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/types.go
pkg/parser/utils.go

Resolves #1500 parser: validate referencees

#1500 parser: validate referencees

---

pkg/istructs/recources-types.go
pkg/projectors/impl.go
pkg/state/impl_async_actualizer_state.go
pkg/state/impl_bundled_host_state_test.go
pkg/state/impl_event_storage_test.go
pkg/state/impl_host_state.go
pkg/state/impl_sync_actualizer_state.go
pkg/state/types.go

Resolves #1688 state: PLogEvent

#1688 state: PLogEvent

---

pkg/iauthnzimpl/impl.go
pkg/iauthnzimpl/impl_test.go
pkg/sys/it/impl_signupin_test.go
pkg/vit/shared_cfgs.go

Resolves #1686 allow the device to work in its profile

#1686 allow the device to work in its profile

---

pkg/utils/mock.go

Resolves #1692 PLogEvent for mocks

#1692 PLogEvent for mocks

---

pkg/sys/builtin/consts.go

Resolves #1699 limit max CUDs by 100

#1699 limit max CUDs by 100

---

pkg/processors/command/impl.go
pkg/vit/impl.go
pkg/vit/types.go

Resolves #1708 VIT add benchmark compatibility

#1708 VIT add benchmark compatibility

---

design/workspaces/invites.md
pkg/sys/invite/consts.go
pkg/sys/invite/impl_initiateinvitationbyemail.go
pkg/sys/it/impl_invite_test.go

Resolves #1704 Unable to reactivate cancelled invitation

#1704 Unable to reactivate cancelled invitation

---

pkg/istorage/mem/impl.go
pkg/istorage/types.go
pkg/istoragecache/impl.go
pkg/vit/impl.go

Resolves #1718 VIT: delay for get and put in tests

#1718 VIT: delay for get and put in tests

---

pkg/processors/command/impl.go

Resolves #1722 manually release the `IPlogEvent` on partition recovery

#1722 manually release the `IPlogEvent` on partition recovery

---

pkg/processors/command/types.go
pkg/projectors/consts.go
pkg/projectors/provide.go
pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #1727 actualizers: set intents limit to 10*MaxCUDs

#1727 actualizers: set intents limit to 10*MaxCUDs

---

pkg/vit/impl.go

Resolves #1732 VIT: set IAppStorage.Get() delay for each app

#1732 VIT: set IAppStorage.Get() delay for each app

---

pkg/sys/collection/collection.go
pkg/vit/impl.go

Resolves #1731 collection: combine in getbatch instead of get for each cud

#1731 collection: combine in getbatch instead of get for each cud

---

pkg/registry/impl_issueprincipaltoken.go

Resolves #1740 q.registru.IssuePrincipalToken: eliminate unused code

#1740 q.registru.IssuePrincipalToken: eliminate unused code

---

pkg/apps/sys/registryapp/const.go
pkg/apps/sys/registryapp/provide.go
pkg/vit/impl_vitcfg.go

Resolves #1743 sys/registry: provide partitions amount from outside

#1743 sys/registry: provide partitions amount from outside

---

pkg/istorage/cas/consts.go
pkg/istorage/cas/impl.go
pkg/istorage/cas/runtests.bash

Resolves #1751 istorage/cas: DefaultConsistency

#1751 istorage/cas: DefaultConsistency

---

pkg/sys/it/impl_invite_test.go

Resolves #1763 VIT: TestInvite_BasicUsage fails sometimes

#1763 VIT: TestInvite_BasicUsage fails sometimes

---

pkg/istructs/recources-types.go
pkg/state/impl_host_state.go
pkg/state/impl_view_records_storage_test.go

Resolves #1780 state: add App() AppQName method

#1780 state: add App() AppQName method

---

go.mod
go.sum
pkg/parser/const.go
pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/sql_example_syspkg/system.sql
pkg/parser/types.go
pkg/parser/utils.go

Resolves #1786 parser: support CRON projectors

#1786 parser: support CRON projectors

---

pkg/registry/impl_resetpassword.go
pkg/router/consts.go
pkg/router/impl_test.go
pkg/sys/invite/impl_applycancelacceptedinvite.go
pkg/sys/invite/impl_applyinvitation.go
pkg/sys/invite/impl_applyjoinworkspace.go
pkg/sys/invite/impl_applyleaveworkspace.go
pkg/sys/invite/impl_applyupdateinviteroles.go
pkg/sys/it/impl_metrics_test.go
pkg/sys/it/reverseproxy_test.go
pkg/sys/verifier/impl.go
pkg/sys/workspace/impl.go
pkg/sys/workspace/impl_buildws.go
pkg/sys/workspace/impl_deactivate.go
pkg/utils/http.go
pkg/utils/http_test.go
pkg/utils/types.go
pkg/vit/impl.go
pkg/vit/utils.go
pkg/vvm/consts.go
pkg/vvm/impl_cfg.go
pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #1784 performance: use cached http client instead of creating it on each federation request

#1784 performance: use cached http client instead of creating it on each federation request

---

pkg/processors/command/impl_test.go
pkg/utils/consts.go
pkg/utils/http.go
pkg/utils/test_utils.go
pkg/utils/utils.go

Resolves #1792 voedger, VIT: retry on error 10061 (connection refused)

#1792 voedger, VIT: retry on error 10061 (connection refused)

---

design/0-inv/20230304-about-EE-design/README.md
design/commandprocessor/README.md
design/consistency/README-v1.md
design/hvm/README.md
design/monitor/metrics.md
design/orchestration/README.md
design/orchestration/app-deployment-2.md
design/state/ext-engines.md
design/storage/README.md
design/workspaces/create-workspace-v2.md
pkg/router/impl_blob.go
pkg/router/provide.go

#1795 HVM -> VVM

---

pkg/utils/mock.go
pkg/utils/mock_test.go

Resolves #1803 coreutils: mocks interfaces compliance

#1803 coreutils: mocks interfaces compliance

---

pkg/utils/copy_test.go

Resolves #1807 coreutils: cover by tests copy.go

#1807 coreutils: cover by tests copy.go

---

cmd/vpm/baseline.go
cmd/vpm/compat.go
cmd/vpm/compile.go
cmd/vpm/const.go
cmd/vpm/init.go
cmd/vpm/orm.go
cmd/vpm/tidy.go

#1824 vpm: refactor

---

pkg/apps/sys/registryapp/provide.go
pkg/vit/impl_vitcfg.go

Resolves #1833 take amount partitions from the same place

#1833 take amount partitions from the same place

---

cmd/vpm/baseline.go
cmd/vpm/compat.go
cmd/vpm/compile.go
cmd/vpm/const.go
cmd/vpm/init.go
cmd/vpm/main.go
cmd/vpm/main_test.go
cmd/vpm/orm.go
cmd/vpm/tidy.go
cmd/vpm/types.go
go.mod

1821 vpm init tidy improvements

---

pkg/router/impl_blob.go
pkg/router/types.go
pkg/vit/impl_vitcfg.go
pkg/vvm/impl_builder.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #1860 routerapp, blobberpapp: exclude from builtin apps

#1860 routerapp, blobberpapp: exclude from builtin apps

---

pkg/apps/sys/blobberapp/provide.go
pkg/apps/sys/clusterapp/provide.go
pkg/apps/sys/registryapp/provide.go
pkg/apps/sys/routerapp/provide.go
pkg/apps/types.go
pkg/istructsmem/appstruct-types.go
pkg/projectors/provide.go
pkg/sys/builtin/impl_echo.go
pkg/sys/builtin/impl_grcount.go
pkg/sys/builtin/impl_modules.go
pkg/sys/builtin/impl_refintegrity.go
pkg/sys/builtin/impl_renameqname.go
pkg/sys/builtin/provide.go
pkg/sys/collection/collection_test.go
pkg/sys/collection/provide.go
pkg/sys/collection/state_func.go
pkg/sys/provide.go
pkg/sys/uniques/provide.go
pkg/sys/workspace/provide.go
pkg/vit/shared_cfgs.go
pkg/vvm/impl_builder.go

Resolves #1876 eliminate IAppDefBuilder on app build

#1876 eliminate IAppDefBuilder on app build

---

pkg/sys/workspace/impl_buildws.go
pkg/sys/workspace/types.go
pkg/utils/objectreader.go
pkg/utils/objectreader_test.go
pkg/utils/types.go

Resolves #1879 Relocate c.sys.CUD body building to coreutils

#1879 Relocate c.sys.CUD body building to coreutils

---

pkg/vvm/impl_builder.go

Resolves #1881 eliminate IAppDef build duplication

#1881 eliminate IAppDef build duplication

---

pkg/appparts/impl.go
pkg/appparts/interface.go
pkg/apppartsctl/impl.go
pkg/vvm/impl_appws.go
pkg/vvm/impl_requesthandler.go

Resolves #1869 router: query: use IAppPartitions.GetPartitionID

#1869 router: query: use IAppPartitions.GetPartitionID

---

pkg/vvm/impl_builder.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #1895 vvm wire: fix order of wiring AppConfigsType

#1895 vvm wire: fix order of wiring AppConfigsType

---

pkg/apps/sys/registryapp/provide.go
pkg/apps/types.go
pkg/vit/consts.go
pkg/vit/impl_vitcfg.go
pkg/vvm/consts.go
pkg/vvm/wire_gen.go

Resolves #1898 voedger: apps: Get rid of apis.NumCommandProcessors

#1898 voedger: apps: Get rid of apis.NumCommandProcessors

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/devops.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/technical-dept.md

Resolves #1929 Modify issue templates

#1929 Modify issue templates

---

pkg/processors/command/impl.go
pkg/utils/files.go

Resolves #1933 CP: eliminate unused workpiece methods

#1933 CP: eliminate unused workpiece methods

---

pkg/iextengine/wazero/impl.go
pkg/iextengine/wazero/impl_benchmark_test.go

Resolves #1935 iextenginewazero: Benchmark_Recover does not work

#1935 iextenginewazero: Benchmark_Recover does not work

---

pkg/iextengine/wazero/impl.go
pkg/iextengine/wazero/impl_test.go

Resolves #1937 iextenginewazero: Invoke: repeat in case of memory overflow

#1937 iextenginewazero: Invoke: repeat in case of memory overflow

---

pkg/sys/it/impl_uniques_test.go
pkg/sys/uniques/errors.go
pkg/sys/uniques/impl.go
pkg/sys/uniques/utils.go
pkg/utils/objectreader.go

Resolves #1946 uniques: implement the way to get the unique record by its unique combination

#1946 uniques: implement the way to get the unique record by its unique combination

---

pkg/goutils/exec/exec.go

Resolves #1947 Daily test suite did not pass

#1947 Daily test suite did not pass

---

pkg/cluster/appws.vsql
pkg/cluster/consts.go
pkg/sys/it/impl_sqlquery_test.go
pkg/vit/impl_vitcfg.go

Resolves #1966 write a test that sends sql request to an another app and wsid

#1966 write a test that sends sql request to an another app and wsid

---

pkg/sys/it/impl_test.go
pkg/vit/impl.go
pkg/vit/utils.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #1964 VIT: implement the way to restart the VIT preserving storage

#1964 VIT: implement the way to restart the VIT preserving storage

---

pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #1976 VVM: return error if `sys/cluster` is not in builtin apps

#1976 VVM: return error if `sys/cluster` is not in builtin apps

---

pkg/vvm/errros.go
pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #1986 VVM: return a special error if failed to start main pipeline

#1986 VVM: return a special error if failed to start main pipeline

---

pkg/goutils/exec/exec_test.go

Resolves #1972 Daily Test failed on 26.04.2024

#1972 Daily Test failed on 26.04.2024

---

cmd/ctool/scripts/drafts/dfs_deploy.sh
cmd/vpm/test/genorm/go.work.sum

draft script for Gluster FS create

1907 ctool dfs research

---

pkg/btstrp/consts.go
pkg/btstrp/impl.go
pkg/utils/consts.go
pkg/utils/http.go
pkg/utils/types.go

failed to start Air on Test cluster
https://dev.untill.com/projects/#!691773

failed to start Air on Test cluster

---

pkg/utils/http.go

Resolves #2009 federation post: fix wrong retriers handling

#2009 federation post: fix wrong retriers handling

---

pkg/parser/README.md
pkg/parser/impl_test.go
pkg/parser/sql_example_app/pmain/package.vsql
pkg/parser/types.go

Resolves #2015 parser: types and aliases

#2015 parser: types and aliases

---

pkg/iextengine/wazero/impl_test.go

Resolves #1957 iextengonewazero: small test fixes

#1957 iextengonewazero: small test fixes

---

cmd/ctool/upgrade.go

Resolves #2019 ctool: upgrade CE

#2019 ctool: upgrade CE

---

pkg/sys/it/impl_resetpassword_test.go
pkg/sys/it/impl_verifier_test.go
pkg/sys/verifier/impl.go

Resolves #2026 remove rate limit on `c.sys.InitiateEmailVerification`

#2026 remove rate limit on `c.sys.InitiateEmailVerification`

---

pkg/utils/appwsid.go
pkg/utils/appwsid_test.go

Implement function AppWSIDToPseudoWSID
https://dev.untill.com/projects/#!692201

Implement function AppWSIDToPseudoWSID

---

pkg/parser/README.md
pkg/parser/impl_test.go
pkg/parser/types.go

Resolves #2035 parser: types and aliases part 2

#2035 parser: types and aliases part 2

---

.github/workflows/cp.yml

#1813 Cherry picking

---

pkg/iextengine/wazero/impl_test.go
pkg/processors/command/impl.go
pkg/processors/command/types.go
pkg/state/impl_cmd_result_storage_test.go
pkg/state/impl_command_processor_state.go
pkg/state/impl_commandcontext_storage.go
pkg/state/impl_commandcontext_storage_test.go
pkg/state/impl_records_storage_test.go
pkg/state/impl_subject_storage_test.go
pkg/state/impl_wlog_storage_test.go
pkg/state/teststate/impl.go
pkg/state/types.go

Resolves #1963 StorageCommandContext: add WLogOffs

#1963 StorageCommandContext: add WLogOffs

---

pkg/exttinygo/consts.go
pkg/state/consts.go
pkg/state/impl_command_processor_state.go
pkg/state/impl_query_processor_state.go
pkg/state/impl_response_storage.go
pkg/state/impl_response_storage_test.go
pkg/state/types.go
pkg/sys/sys.vsql

Resolves #2040 StorageResult: support status code

#2040 StorageResult: support status code

---

pkg/sys/it/race_n10n_test.go

Resolves #2069 fix datarace in Test_Race_n10nCHS()
Resolves https://github.com/voedger/voedger/issues/2067
Resolves #2060

#2069 fix datarace in Test_Race_n10nCHS()

---

pkg/router/impl_test.go

Resolves #2073 fix TestFailedToWriteResponse()

#2073 fix TestFailedToWriteResponse()

---

pkg/sys/it/impl_resetpassword_test.go
pkg/sys/it/impl_verifier_test.go
pkg/sys/verifier/impl.go

Resolves #2089 temporary remove rate limit on c.sys.InitiateEmailVerification

#2089 temporary remove rate limit on c.sys.InitiateEmailVerification

---

pkg/router/consts.go
pkg/router/impl_test.go
pkg/router/utils.go

Resolves #2085 fix TestFailedToWriteResponse()

#2085 fix TestFailedToWriteResponse()

---

.gitattributes

Resolves #2098 highlight vsql files on github

#2098 highlight vsql files on github

---

pkg/istructs/utils.go
pkg/istructs/utils_test.go
pkg/sys/sqlquery/impl.go
pkg/sys/sqlquery/impl_plog.go
pkg/sys/sqlquery/impl_wlog.go
pkg/utils/objectreader.go

Resolves #2105 add logging if failed to read the event on sql query

#2105 add logging if failed to read the event on sql query

---

pkg/sys/it/impl_bootstrap_test.go

Resolves #2116 fix TestBoostrap_BasicUsage()

#2116 fix TestBoostrap_BasicUsage()

---

staging/src/github.com/untillpro/ibusmem/impl.go

Resolves #2119 fix TestHandlerPanic()

#2119 fix TestHandlerPanic()

---

pkg/exttinygo/consts.go

2123 exttinygo add storagefederationcommand

---

.github/ISSUE_TEMPLATE/quality.md

Resolves #2104 Issue type: Quality

#2104 Issue type: Quality

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go

Resolves #2133 parser: field from fieldset not found when listed in UNIQUE

#2133 parser: field from fieldset not found when listed in UNIQUE

---

pkg/state/teststate/testsys/system.sql

Resolves #2135 teststate: FederationCommand not available

#2135 teststate: FederationCommand not available

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go

Resolves #2137 parser: invaild memory address

#2137 parser: invaild memory address

---

pkg/state/teststate/consts.go
pkg/state/teststate/impl.go
pkg/state/teststate/interface.go
pkg/state/teststate/testsys/system.sql

Resolves #2143 teststate: improvements

#2143 teststate: improvements

---

pkg/istructs/recources-types.go
pkg/state/impl_bundled_host_state.go
pkg/state/teststate/impl.go
pkg/state/teststate/interface.go
pkg/state/types.go

2154 teststate compare intents

---

pkg/state/teststate/impl.go
pkg/state/teststate/interface.go

Resolves #2167 teststate: method to get record

#2167 teststate: method to get record

---

pkg/cluster/impl_updatecorrupted.go
pkg/sys/it/impl_vsqlupdate_test.go

Resolves #2195 update corrupted: return error if the event does not exist

#2195 update corrupted: return error if the event does not exist

---

pkg/sys/it/impl_resetpassword_test.go
pkg/sys/it/impl_verifier_test.go
pkg/sys/verifier/impl.go

Resolves #2090 return back rate limits on c.sys.InitiateEmailVerification

#2090 return back rate limits on c.sys.InitiateEmailVerification

---

pkg/istructsmem/event-types.go
pkg/istructsmem/event-types_test.go

Resolves #2204 IObject.FillFromJSON: support nil

#2204 IObject.FillFromJSON: support nil

---

pkg/cluster/errors.go
pkg/cluster/impl_update.go
pkg/sys/it/impl_vsqlupdate_test.go

Resolves #2206 VSqlUpdate: deny null values

#2206 VSqlUpdate: deny null values

---

pkg/vvm/provide.go

Resolves #2215 compilation fix

#2215 compilation fix

---

pkg/state/types.go

Resolves #2233 StorageWLog: add ArgumentObject

#2233 StorageWLog: add ArgumentObject

---

cmd/ctool/ce.go

Resolves #2237 ctool: CE: do not reset voedger's password

#2237 ctool: CE: do not reset voedger's password

---

pkg/sys/it/impl_uniques_test.go

Resolves #2239 uniques: cover a case when no value is provided for nullable unique field

#2239 uniques: cover a case when no value is provided for nullable unique field

---

pkg/iauthnzimpl/consts.go
pkg/iauthnzimpl/impl_acl.go
pkg/iauthnzimpl/types.go
pkg/sys/it/impl_childworkspace_test.go

Add air.SubscriptionReseller role
https://dev.untill.com/projects/#!694587

Add air.SubscriptionReseller role

---

pkg/state/impl_uniques_storage.go

Resolves #2245 StorageUniq: incorrect uniques handler handling

#2245 StorageUniq: incorrect uniques handler handling

---

pkg/state/impl_federation_cmd_storage.go

Resolves #2249 StorageFederationPost: error when status != 200

#2249 StorageFederationPost: error when status != 200

---

pkg/istorage/provider/impl.go
pkg/sys/it/impl_bootstrap_test.go
pkg/vit/impl.go
pkg/vit/utils.go

Resolves #2261 VIT: fix restarting preserving storage

#2261 VIT: fix restarting preserving storage

---

pkg/exttinygo/consts.go
pkg/state/consts.go
pkg/state/errors.go
pkg/state/impl.go
pkg/state/impl_async_actualizer_state.go
pkg/state/impl_federation_blob_storage.go
pkg/state/impl_federation_blob_storage_test.go
pkg/state/impl_query_processor_state.go
pkg/state/teststate/testsys/system.sql
pkg/state/types.go
pkg/sys/sys.vsql

Resolves #2267 Storage FederationBlob

#2267 Storage FederationBlob

---

pkg/state/impl_federation_blob_storage.go

Resolves #2275 Storage FederationBlob: ReadCloser -> Body

#2275 Storage FederationBlob: ReadCloser -> Body

---

pkg/ibus/interface.go
pkg/ihttp/interface.go
pkg/router/impl_http.go
pkg/router/impl_test.go
staging/src/github.com/untillpro/airs-ibus/errors.go
staging/src/github.com/untillpro/airs-ibus/interface.go
staging/src/github.com/untillpro/ibusmem/impl.go
staging/src/github.com/untillpro/ibusmem/impl_test.go

Resolves #2266 perftest: request failed

#2266 perftest: request failed

---

pkg/router/impl_test.go

Resolves #2265 Daily Test failed on 08/06/2024 05:22

#2265 Daily Test failed on 08/06/2024 05:22

---

pkg/router/impl_test.go
pkg/router/utils.go

Resolves #2132 fix router tests

#2132 fix router tests

---

pkg/cluster/consts.go
pkg/cluster/impl_updateunlogged.go
pkg/cluster/impl_vsqlupdate.go
pkg/dml/consts.go
pkg/dml/impl.go
pkg/dml/impl_test.go
pkg/sys/it/impl_vsqlupdate_test.go

Resolves #2289 Use `UNLOGGED UPDATE` syntax instead of `DIRECT UPDATE`

#2289 Use `UNLOGGED UPDATE` syntax instead of `DIRECT UPDATE`

---

pkg/state/impl_federation_blob_storage.go
pkg/state/teststate/impl.go
pkg/state/teststate/interface.go

Resolves #2288 teststate: support FederationBlobHandler

#2288 teststate: support FederationBlobHandler

---

pkg/parser/impl_analyse.go
pkg/parser/impl_test.go
pkg/parser/utils.go

Resolves #1773 parser: type visibility: derived workspace shall see types from base workspace

#1773 parser: type visibility: derived workspace shall see types from base workspace

---

cmd/ctool/acme.go
cmd/ctool/alert.go
cmd/ctool/backup.go
cmd/ctool/cluster.go
cmd/ctool/init.go
cmd/ctool/main.go
cmd/ctool/mon.go
cmd/ctool/repeat.go
cmd/ctool/replace.go
cmd/ctool/restore.go
cmd/ctool/scripts.go
cmd/ctool/validate.go
pkg/goutils/cobrau/rootcmd.go

Resolves #2296 Storage: Modbus device storage

#2296 Storage: Modbus device storage

---

pkg/registry/appws.vsql
pkg/registry/consts.go
pkg/registry/impl_issueprincipaltoken.go
pkg/sys/authnz/consts.go
pkg/sys/it/impl_signupin_test.go

Resolves #2304 autnz: short-lived tokens

#2304 autnz: short-lived tokens

---

pkg/sys/authnz/consts.go

Resolves #2311 authnz: make max token TTL 1 week

#2311 authnz: make max token TTL 1 week

---

pkg/istructs/recources-types.go
pkg/state/impl_host_state.go
pkg/state/teststate/impl.go
pkg/state/teststate/interface.go
pkg/utils/mock.go

Resolves #2185 teststate: NotExists Intent assertion

#2185 teststate: NotExists Intent assertion

---

cmd/vpm/test/build/appsimple/wasm/bench_test.go
examples/airs-bp/air/extwasm/bench_test.go
pkg/appdef/impl_container.go
pkg/appdef/impl_data.go
pkg/appdef/impl_data_test.go
pkg/appdef/impl_extension.go
pkg/appdef/impl_extension_test.go
pkg/appdef/impl_field.go
pkg/appdef/impl_projector.go
pkg/appdef/impl_type_test.go
pkg/appdef/utils_projector_test.go
pkg/appdef/utils_types.go
pkg/appparts/impl_processorkind.go
pkg/exttinygo/require/impl.go
pkg/istructs/utils.go
pkg/istructs/utils_test.go
pkg/registry/consts.go
pkg/registry/impl_invokecreateworkspaceid.go
pkg/utils/appwsid.go
pkg/utils/utils.go
pkg/utils/utils/consts.go
pkg/utils/utils/utils.go
pkg/utils/utils/utils_test.go
pkg/vvm/impl_cfg.go
pkg/vvm/metrics/impl.go

Resolves #2309 refactor: UIntToString

#2309 refactor: UIntToString

---

pkg/router/consts.go
pkg/router/impl_blob.go

Resolves #2324 router: use uitls.IntToString()

#2324 router: use uitls.IntToString()

---

cmd/vpm/build.go
cmd/vpm/init.go

2327 vpm build fails during building airs fiscalcloud

---

pkg/parser/impl.go
pkg/parser/utils.go
pkg/state/teststate/consts.go
pkg/state/teststate/impl.go

Resolves #2329 teststate: updates to match app structure

#2329 teststate: updates to match app structure

---

pkg/processors/command/impl.go
pkg/processors/command/provide.go
pkg/processors/query/impl.go
pkg/processors/utils.go
pkg/state/impl_response_storage.go
pkg/sys/it/impl_test.go
pkg/vit/schemaTestApp1.vsql
pkg/vit/shared_cfgs.go

Resolves #2065 support sys.Response in CP and QP

#2065 support sys.Response in CP and QP

---

pkg/iextengine/interface.go
pkg/iextengine/wazero/impl.go
pkg/iextengine/wazero/impl_test.go

Resolves #2339 iextenginewazero: add voedger_wasm_invocations_seconds metric

#2339 iextenginewazero: add voedger_wasm_invocations_seconds metric

---

cmd/vpm/const.go
cmd/vpm/init.go

2341 vpm init and tidy have conflicts in case gomod exists

---

pkg/compile/impl.go

Resolves #2354 vpm compile: clarify error messages

#2354 vpm compile: clarify error messages

---

pkg/appparts/impl_app.go

Resolves #2353 eliminate link to parent pool in `appparts.engines` struct

#2353 eliminate link to parent pool in `appparts.engines` struct

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/types.go
pkg/parser/utils.go

Resolves #2165 IStateValue: refactoring

#2165 IStateValue: refactoring

---

pkg/router/impl_http.go
pkg/router/types.go

Resolves #2386 fix data race on http listener between async projectors and public endpoint start

#2386 fix data race on http listener between async projectors and public endpoint start

---

.github/workflows/integration-test-se.yml
cmd/ctool/scripts/terraform/cluster.tf

Update terraform infrastructure

---

pkg/apps/sys/blobberapp/provide.go
pkg/apps/sys/clusterapp/provide.go
pkg/apps/sys/registryapp/provide.go
pkg/apps/sys/routerapp/provide.go
pkg/apps/utils.go
pkg/cluster/provide.go
pkg/parser/types.go
pkg/registry/provide.go
pkg/sys/it/impl_bootstrap_test.go
pkg/sys/provide.go
pkg/vit/shared_cfgs.go
pkg/vvm/impl_builder.go

Resolves #2420 rename parser.PackageFS.PackageFQN -> .Path

#2420 rename parser.PackageFS.PackageFQN -> .Path

---

cmd/vpm/const.go
cmd/vpm/orm.go
pkg/appparts/impl_app.go
pkg/appparts/interface.go
pkg/pipeline/errors.go
pkg/pipeline/fork-operator-impl.go
pkg/pipeline/fork-operator-impl_test.go
pkg/pipeline/impl_test.go
pkg/pipeline/interface.go
pkg/pipeline/noop-impl.go
pkg/pipeline/noop-impl_test.go
pkg/pipeline/service-operator-impl.go
pkg/pipeline/switch-operator-impl.go
pkg/pipeline/switch-operator-impl_test.go
pkg/pipeline/sync-helpers_test.go
pkg/pipeline/sync-pipeline-impl.go
pkg/pipeline/sync-pipeline-impl_test.go
pkg/pipeline/sync_test.go
pkg/pipeline/types.go
pkg/pipeline/wired-operator.go
pkg/processors/command/impl.go
pkg/processors/command/provide.go
pkg/processors/query/impl.go
pkg/projectors/impl.go
pkg/projectors/impl_helpers_test.go
pkg/sys/collection/collection_utils_test.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

2430 pipeline use iworkpiece instead if anyinterface

---

pkg/state/errors.go
pkg/state/impl_app_secrets_storage.go
pkg/state/impl_app_secrets_storage_test.go
pkg/state/impl_bundled_host_state_test.go
pkg/state/impl_commandcontext_storage.go
pkg/state/impl_event_storage.go
pkg/state/impl_federation_blob_storage.go
pkg/state/impl_federation_cmd_storage.go
pkg/state/impl_host_state_test.go
pkg/state/impl_http_storage.go
pkg/state/impl_http_storage_test.go
pkg/state/impl_querycontext_storage.go
pkg/state/impl_records_storage.go
pkg/state/impl_response_storage.go
pkg/state/impl_response_storage_test.go
pkg/state/impl_result_storage.go
pkg/state/impl_result_storage_test.go
pkg/state/impl_send_mail_storage.go
pkg/state/impl_send_mail_storage_test.go
pkg/state/impl_subject_storage.go
pkg/state/impl_test.go
pkg/state/impl_uniques_storage.go
pkg/state/impl_view_records_storage_test.go
pkg/state/impl_wlog_storage.go
pkg/state/impl_wlog_storage_test.go
pkg/state/types.go
pkg/state/types_test.go
pkg/vit/shared_cfgs.go

Resolves #2063 state: keys and builders improvements

#2063 state: keys and builders improvements

---

pkg/iauthnzimpl/impl_acl.go

Resolves #2474 grant select on field q.sys.State.State to role.air.BOReader

#2474 grant select on field q.sys.State.State to role.air.BOReader

---

cmd/vpm/test/build/noappschema/packages_gen.go
cmd/vpm/test/genorm/mypkg5/packages_gen.go

2486 eliminate unnecessary dependencies on untillproairs bp3 in vpm

---

pkg/sys/it/impl_sqlquery_test.go
pkg/sys/sqlquery/impl.go
pkg/utils/http.go

Resolves #2500 sqlquery: log response from the forwarded query

#2500 sqlquery: log response from the forwarded query

---

cmd/ctool/scripts.go
pkg/utils/zip.go

1991 osstat everywhere correct err handling

---

pkg/sys/sqlquery/impl.go

Resolves #2505 sqlquery: revert response from forwarded query logging

#2505 sqlquery: revert response from forwarded query logging

---

pkg/sys/it/impl_sqlquery_test.go
pkg/utils/http.go

Resolves #2532 sqlquery: index out of range on empty result in different app

#2532 sqlquery: index out of range on empty result in different app

---

.gitignore
cmd/vpm/baseline.go
cmd/vpm/build.go
cmd/vpm/main.go
cmd/vpm/main_test.go
pkg/goutils/cobrau/catch_interrupt.go
pkg/goutils/cobrau/rootcmd.go

Resolves #2541 vpm: improve messages

#2541 vpm: improve messages

---

pkg/istructsmem/resources-types.go
pkg/processors/query/impl.go

Resolves #2553 QP: eliminate stored IQueryFunction

#2553 QP: eliminate stored IQueryFunction

---

pkg/processors/actualizers/actualizers.go
pkg/processors/actualizers/async.go
pkg/processors/actualizers/interface.go
pkg/processors/schedulers/impl_scheduler.go
pkg/processors/schedulers/impl_schedulers.go
pkg/processors/schedulers/interface.go

Resolves #2555 ISchedulerRunner, IActualizerRunner: eliminate IAppPartitions from the config

#2555 ISchedulerRunner, IActualizerRunner: eliminate IAppPartitions from the config

---

design/api/README.md

2512 clarify syntax of responses in apiv2

---

pkg/processors/schedulers/impl_scheduler.go
pkg/utils/time.go
pkg/utils/time_test.go

Resolves #2571 fix timers firing

#2571 fix timers firing

---

pkg/exttinygo/consts.go
pkg/state/stateprovide/impl_async_actualizer_state.go
pkg/state/stateprovide/impl_command_processor_state.go
pkg/state/stateprovide/impl_query_processor_state.go
pkg/state/stateprovide/impl_sync_actualizer_state.go
pkg/state/teststate/testsys/system.sql
pkg/sys/const.go
pkg/sys/storages/impl_logger_storage.go
pkg/sys/storages/impl_logger_storages_test.go
pkg/sys/sys.vsql

Resolves #2580 StateStorage for Logging

#2580 StateStorage for Logging

---

pkg/sys/storages/impl_wlog_storage.go
pkg/sys/storages/impl_wlog_storage_test.go

Resolves #2591 WLogStorage: Get operation must not work through Read

#2591 WLogStorage: Get operation must not work through Read

---

pkg/sys/storages/impl_http_storage.go

Resolves #2593 StateStorageHttp: add logging

#2593 StateStorageHttp: add logging

---

pkg/istructs/consts.go

Resolves #2595 add ClusterAppID for fiscalcloud app

#2595 add ClusterAppID for fiscalcloud app

---

pkg/vit/impl.go
pkg/vit/impl_vitcfg.go
pkg/vit/types.go

Resolves #2613 VIT: specify custom secrets in VIT config

#2613 VIT: specify custom secrets in VIT config

---

pkg/isecretsimpl/provide.go
pkg/isecretsimpl/test_utils.go
pkg/itokensjwt/test_utils.go
pkg/processors/query/impl.go
pkg/processors/query/impl_test.go
pkg/processors/query/interface.go
pkg/processors/query/query-params-impl_test.go
pkg/sys/collection/collection_test.go
pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #2620 QP: use the actual Secrets Reader

#2620 QP: use the actual Secrets Reader

---

pkg/iextengine/wazero/impl_helpers_test.go
pkg/istructs/recources-types.go
pkg/processors/query/impl_test.go
pkg/state/stateprovide/impl_host_state.go
pkg/state/stateprovide/impl_host_state_test.go
pkg/state/stateprovide/impl_test.go
pkg/state/stateprovide/types_test.go
pkg/sys/storages/impl_app_secrets_storage.go
pkg/sys/storages/impl_commandcontext_storage.go
pkg/sys/storages/impl_event_storage.go
pkg/sys/storages/impl_federation_blob_storage.go
pkg/sys/storages/impl_federation_cmd_storage.go
pkg/sys/storages/impl_http_storage.go
pkg/sys/storages/impl_jobcontext_storage.go
pkg/sys/storages/impl_logger_storage.go
pkg/sys/storages/impl_querycontext_storage.go
pkg/sys/storages/impl_records_storage.go
pkg/sys/storages/impl_response_storage.go
pkg/sys/storages/impl_result_storage.go
pkg/sys/storages/impl_send_mail_storage.go
pkg/sys/storages/impl_subject_storage.go
pkg/sys/storages/impl_uniques_storage.go
pkg/sys/storages/impl_view_records_storage.go
pkg/sys/storages/impl_wlog_storage.go
pkg/sys/storages/impl_wlog_storage_test.go
pkg/sys/storages/types.go

#2619  state: unclear error message on MustExist

---

pkg/registry/impl_createlogin.go
pkg/sys/it/impl_signupin_test.go
pkg/sys/it/impl_workspace_test.go
pkg/sys/workspace/impl.go
pkg/vit/utils.go

Resolves #2415 aproj.sys.ApplyInvokeCreateWorkspaceID could stuck on e.g. create a login in an unknown app

#2415 aproj.sys.ApplyInvokeCreateWorkspaceID could stuck on e.g. create a login in an unknown app

---

cmd/vpm/build.go
cmd/vpm/main_test.go
pkg/coreutils/zip.go
pkg/coreutils/zip_test.go

Resolves #2213 coreutils: refactor zip

#2213 coreutils: refactor zip

---

pkg/pipeline/async.go
pkg/pipeline/async_test.go

2652 eliminate asyncgoflushtimer

---

pkg/iextengine/builtin/impl.go
pkg/iextengine/builtin/impl_test.go

Resolves #2666 clarify extension panic

#2666 clarify extension panic

---

pkg/iextengine/wazero/const.go
pkg/iextengine/wazero/impl.go
pkg/iextengine/wazero/impl_test.go

Resolves #2669 provide wasm engine metrics

#2669 provide wasm engine metrics

---

.golangci.yml

Resolves #2683 cleanup .golangci.yml

#2683 cleanup .golangci.yml

---

go.mod
go.sum

Resolves #2701 update dynobuffers

#2701 update dynobuffers

---

go.mod
go.sum
pkg/state/smtptest/impl.go
pkg/state/smtptest/types.go

#2704 update go-smtp

---

pkg/vit/mock/impl.go

Resolves #2709 update mocks for new iterators

#2709 update mocks for new iterators

---

go.mod
go.sum

#2712 update deps

---

pkg/coreutils/utils.go
pkg/ctrlloop/utils.go
pkg/pipeline/async.go

Resolves #2714 eliminate `coreutils.ResetTimer`

#2714 eliminate `coreutils.ResetTimer`

---

pkg/processors/actualizers/async.go
pkg/processors/actualizers/impl.go
pkg/processors/actualizers/types.go
pkg/processors/actualizers/types_test.go

Resolves #2716 projectors: log if the projector is acceptable to the event

#2716 projectors: log if the projector is acceptable to the event

---

pkg/vvm/types.go

Resolves #2719 VIT: amend coment on VVMConfig.KeyspaceNameSuffix

#2719 VIT: amend coment on VVMConfig.KeyspaceNameSuffix

---

pkg/istructsmem/resources-types.go
pkg/processors/actualizers/provide.go
pkg/processors/query/impl.go
pkg/vvm/engines/impl.go

Resolves #2730 IStatelessResources: adapt to new iterators

#2730 IStatelessResources: adapt to new iterators

---

pkg/processors/command/impl.go
pkg/processors/command/impl_test.go
pkg/processors/command/provide.go
pkg/processors/command/types.go
pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #2733 CP uses the its order number as PartitionID, not the PartitionID came in the request

#2733 CP uses the its order number as PartitionID, not the PartitionID came in the request

---

pkg/istorage/cas/impl.go

Resolves #1394 storage: cas: avoid memory additional allocation on `GetBatch()`

#1394 storage: cas: avoid memory additional allocation on `GetBatch()`

---

pkg/sys/invite/impl_applyjoinworkspace.go
pkg/sys/invite/impl_initiateinvitationbyemail.go
pkg/sys/invite/utils.go

Resolves #2751 aproj.sys.ApplyJoinWorkspace: subject exists already -> skip: add logs

#2751 aproj.sys.ApplyJoinWorkspace: subject exists already -> skip: add logs

---

pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #2753 eliminate VVMConfig.Quotas

#2753 eliminate VVMConfig.Quotas

---

pkg/vvm/consts.go

Resolves #2756 increase n10n number of channels quota

#2756 increase n10n number of channels quota

---

pkg/processors/query/impl.go
pkg/processors/query/impl_test.go
pkg/processors/query/interface.go
pkg/processors/query/operator-enrichment-impl.go
pkg/processors/query/operator-send-to-bus-impl.go
pkg/processors/query/operator-send-to-bus-impl_test.go
pkg/sys/it/bug_test.go

Resolves #2759 QP: fix panic on an unknown field in referenced table

#2759 QP: fix panic on an unknown field in referenced table

---

pkg/iextengine/wazero/impl.go
pkg/iextengine/wazero/impl_test.go

2672 log wasms engine recovery info

---

pkg/istructsmem/event-types.go
pkg/istructsmem/types.go
pkg/istructsmem/types_test.go
pkg/processors/consts.go
pkg/processors/errors.go

Resolves #2775 FillFromJSON: worng type is provided -> describe the field

#2775 FillFromJSON: wrong type is provided -> describe the field

---

pkg/cluster/impl_updateunlogged.go
pkg/coreutils/http.go
pkg/coreutils/maps.go
pkg/processors/command/impl.go
pkg/sys/it/impl_cud_test.go
pkg/sys/it/impl_test.go

Resolves #2773 Nullability: Study how zero values are kept in modified fields

#2773 Nullability: Study how zero values are kept in modified fields

---

pkg/parser/impl_test.go
pkg/parser/utils.go

2797 parser unexpected circular reference errors

---

pkg/istructsmem/errors.go
pkg/istructsmem/event-types.go
pkg/istructsmem/event-types_test.go
pkg/processors/command/impl.go
pkg/processors/command/provide.go
pkg/sys/it/impl_test.go
pkg/sys/it/impl_uniques_test.go
pkg/vit/schemaTestApp1.vsql

Resolves #2814 CP: revert #2784 (do not allow nulls)

#2814 CP: revert #2784 (do not allow nulls)

---

pkg/state/teststate/testsys/system.sql

Resolves #2828 update teststate/.../system.sql

#2828 update teststate/.../system.sql

---

cmd/vpm/test/build/appsimple/wasm/orm/package_air.go
cmd/vpm/test/build/appsimple/wasm/orm/package_untill.go
cmd/vpm/test/genorm/mypkg1/mypkg1.vsql
examples/airs-bp/README.md
examples/airs-bp/air/extwasm/orm/package_air.go
examples/airs-bp/air/extwasm/orm/package_untill.go
examples/airs-bp2/air/air.vsql
examples/airs-bp2/untill/untill.vsql
pkg/appdefcompat/testdata/sys.new.vsql
pkg/appdefcompat/testdata/sys.old.vsql
pkg/iextengine/wazero/_testdata/basicusage/package.sql
pkg/iextengine/wazero/_testdata/tests/package.sql
pkg/iextengine/wazero/sql_example_syspkg/system.vsql
pkg/parser/impl_test.go
pkg/parser/sql_example_syspkg/system.vsql
pkg/state/teststate/testsys/system.sql
pkg/sys/it/testdata/apps/test2.app1/image/pkg/sys/sys.vsql
pkg/sys/it/testdata/apps/test2.app1/image/pkg/sys/userprofile.vsql
pkg/sys/sys.vsql
pkg/sys/userprofile.vsql

Resolves #2834 VSQL: explicit use sys package

#2834 VSQL: explicit use sys package

---

pkg/appdef/impl_appdef.go
pkg/appdef/impl_type.go
pkg/appdef/impl_workspace.go

Resolves #2841 appdef: fix linter errors

#2841 appdef: fix linter errors

---

cmd/vpm/main_test.go
cmd/vpm/testdata/build/air/app.vsql
pkg/state/teststate/interface_new.go

2850 use go mod edit instead self made function replacepackagebylocalpath

---

pkg/appparts/internal/actualizers/actualizers.go
pkg/appparts/internal/actualizers/actualizers_test.go
pkg/appparts/internal/actualizers/example_test.go
pkg/appparts/internal/schedulers/example_test.go
pkg/appparts/internal/schedulers/schedulers.go
pkg/appparts/internal/schedulers/schedulers_test.go

Resolves #2857 appparts/actualizers: fix rt state

#2857 appparts/actualizers: fix rt state

---

cmd/vpm/const.go

2820 why vpm build generates build folder ref airs bp3appsfiscalcloudbuildcmd

---

pkg/appparts/internal/actualizers/actualizers.go
pkg/appparts/internal/schedulers/schedulers.go

Resolves #2870 appparts/actualizers: elimiate RW mutexes

#2870 appparts/actualizers: elimiate RW mutexes

---

pkg/sys/it/impl_jobs_test.go
pkg/sys/it/testdata/apps/test2.app1/src/build.sh
pkg/vit/schemaTestApp2WithJob.vsql
pkg/vit/shared_cfgs.go

Resolves #2869 jobs integration test: watch on logger -> wath on view

#2869 jobs integration test: watch on logger -> wath on view

---

pkg/appdef/impl_workspace.go
pkg/appdef/impl_workspace_test.go
pkg/appdef/interface_workspace.go

Resolves #2872 appdef: do not enum types from used workspaces

#2872 appdef: do not enum types from used workspaces

---

pkg/sys/it/impl_jobs_test.go

Resolves #2877 fix jobs in sidecar app test

#2877 fix jobs in sidecar app test

---

pkg/sys/it/impl_jobs_test.go

Resolves #2880 fix TestJobs_BasicUsage_Sidecar()

#2880 fix TestJobs_BasicUsage_Sidecar()

---

pkg/sys/invite/impl_initiateinvitationbyemail.go
pkg/sys/it/impl_jobs_test.go

Resolves #2883 fix TestJobjs_BasicUsage_Builtin()
Resolves #2882

#2883 fix TestJobjs_BasicUsage_Builtin()

---

pkg/iblobstoragestg/impl.go
pkg/iblobstoragestg/impl_test.go

Resolves #2887 BLOBs: simplify buckets number mdification in the BLOB key

#2887 BLOBs: simplify bucket number modification in the BLOB key

---

cmd/vpm/build.go

Resolves #2896 vpm build: provide hints for known errors on tinygo exec

#2896 vpm build: provide hints for known errors on tinygo exec

---

pkg/iblobstorage/impl_test.go
pkg/iblobstoragestg/impl.go
pkg/iblobstoragestg/impl_test.go

Resolves #2916 ammend tests in `iblobstorage` package

#2916 ammend tests in `iblobstorage` package

---

cmd/vpm/main_test.go
cmd/vpm/orm.go

Resolves #2901 vpm orm: fix wrong orm generation
Resolves #2895

#2901 vpm orm: fix wrong orm generation

---

pkg/coreutils/federation/impl.go
pkg/coreutils/federation/interface.go
pkg/coreutils/federation/types.go
pkg/iblobstorage/types.go
pkg/sys/workspace/impl_buildws.go
pkg/vit/impl.go

Resolves #2919 relocate BLOBReader federation -> iblobstorage

#2919 relocate BLOBReader federation -> iblobstorage

---

pkg/iblobstorage/utils_test.go

Resolves #2921 improve TestNewSUUID

#2921 improve TestNewSUUID

---

go.mod
go.work

Resolves #2940 clean root go.work
Resolves #2939

#2940 clean root go.work

---

pkg/iauthnzimpl/consts.go
pkg/iauthnzimpl/impl_acl.go

Resolves #2943 allow to read some docs via `q.sys.Collection`

#2943 allow to read some docs via `q.sys.Collection`

---

pkg/iauthnzimpl/impl_acl.go

#2945 update ACL

---

pkg/iauthnzimpl/consts.go
pkg/iauthnzimpl/impl.go
pkg/iauthnzimpl/impl_acl.go
pkg/iauthnzimpl/impl_test.go

Resolves #2949 update ACL: cdoc.air.AirReseller

#2949 update ACL: cdoc.air.AirReseller

---

pkg/iauthnzimpl/impl_acl.go

Resolves #2957 updateACL: c.air.LinkDeviceToRestaurant

#2957 updateACL: c.air.LinkDeviceToRestaurant

---

pkg/iauthnzimpl/consts.go
pkg/iauthnzimpl/impl_acl.go

Resolves #2960 update ACL: cdoc.air.Reseller

#2960 update ACL: cdoc.air.Reseller

---

pkg/iauthnzimpl/impl_acl.go

Resolves #2963 update ACL: cdoc.air.UntillPayments

#2963 update ACL: cdoc.air.UntillPayments

---

pkg/coreutils/http.go

Resolves #2968 implement `Expect423()` VIT functional option

#2968 implement `Expect423()` VIT functional option

---

pkg/ihttpimpl/impl.go
pkg/router/consts.go
pkg/router/impl_apiv2.go
pkg/router/impl_blob.go
pkg/router/impl_http.go
pkg/router/impl_sections.go
pkg/router/impl_test.go
pkg/router/provide.go
pkg/router/utils.go
pkg/vvm/provide.go
pkg/vvm/wire_gen.go
staging/src/github.com/untillpro/airs-ibus/interface.go
staging/src/github.com/untillpro/airs-ibus/types.go

Resolves #2956 Router: implement new routes

#2956 Router: implement new routes

---

pkg/iauthnzimpl/impl_acl.go

Resolves #2978 update ACL: sys.ChildWorkspace

#2978 update ACL: sys.ChildWorkspace

---

pkg/iauthnzimpl/impl_acl.go

Resolves #2980 updateACL: allow sys.ChidWorkspace rule

#2980 updateACL: allow sys.ChidWorkspace rule

---

pkg/router/impl_blob.go

Resolves #2988 blobber: add logs

#2988 blobber: add logs

---

pkg/router/impl_blob.go
pkg/router/impl_http.go

Resolves #2990 fix https service prepare\run workflow
Resolves #2990 fix https service prepare\run workflow

#2990 fix https service prepare\run workflow

---

cmd/vpm/ormtemplates/methods.gotmpl
pkg/exttinygo/impl_keybuilder.go
pkg/exttinygo/internal/impl_state_tinygo.go
pkg/state/isafestateapi/interface.go
pkg/state/safestate/impl.go
pkg/state/teststate/impl_new.go
pkg/sys/storages/impl_mocked_storage.go

2987 refactoring putint64id id putrecordidsysstorage record field id id in mockedkeybuilder and mockedvaluebuilder

---

cmd/vpm/build.go

2825 vpm do not use logger to log errors

---

pkg/coreutils/federation/impl.go
pkg/iauthnzimpl/consts.go
pkg/iauthnzimpl/impl_acl.go
pkg/router/impl_blob.go
pkg/sys/it/impl_blob_test.go

Resolves #3007 make temporary blob write be awailable in demo locations without authorization

#3007 make temporary blob write be awailable in demo locations without authorization

---

pkg/processors/command/impl.go
pkg/processors/query/impl.go

Resolves #3011 processors: temporary suppress `role not found` error

#3011 processors: temporary suppress `role not found` error

---

pkg/iauthnzimpl/impl_acl.go

Resolves #3013 updateACL: allow select `cdoc.air.Reseller`

#3013 updateACL: allow select `cdoc.air.Reseller`

---

pkg/processors/command/impl.go
pkg/processors/query/impl.go
pkg/sys/it/impl_test.go

Resolves #3018 update ACL: temporary disable SELECT rule checking

#3018 update ACL: temporary disable SELECT rule checking

---

pkg/irates/interface.go
pkg/iratesce/impl.go
pkg/iratesce/impl_test.go
pkg/iratesce/provide.go
pkg/iratesce/race_test.go
pkg/iratesce/types.go
pkg/istructsmem/impl.go
pkg/istructsmem/ratelimits-types.go
pkg/istructsmem/ratelimits-types_test.go
pkg/vit/impl.go

Resolves #3027 irates: IBuckets.TakeTokens() should return exceeded limit

#3027 irates: IBuckets.TakeTokens() should return exceeded limit

---

cmd/vpm/main_test.go
cmd/vpm/testdata/build/air/go.sum
cmd/vpm/testdata/build/air/wasm/main_test.go
pkg/exttinygo/exttinygotests/impl.go
pkg/state/teststate/impl_new.go
pkg/sys/storages/impl_mocked_storage.go

3038 fix testgenormforairapp

---

cmd/vpm/main_test.go
cmd/vpm/testdata/build/air/go.mod

3045 fix testbuildbasicusage

---

pkg/itokens-payloads/types.go
pkg/processors/command/impl.go
pkg/router/impl_sections.go
pkg/sys/it/bug_test.go
pkg/sys/it/impl_workspace_test.go
pkg/sys/workspace/impl.go

Resolves #3046 router: fix pseudoWSID determination

#3046 router: fix pseudoWSID determination

---

pkg/itokens-payloads/types.go
pkg/processors/command/impl.go
pkg/sys/workspace/impl.go

Resolves #3051 eliminate non-required comments

#3051 eliminate non-required comments

---

pkg/appdef/impl_appdef.go
pkg/appdef/impl_field_test.go
pkg/appdef/impl_function_test.go
pkg/appdef/impl_gdoc_test.go
pkg/appdef/impl_job_test.go
pkg/appdef/impl_object_test.go
pkg/appdef/impl_odoc_test.go
pkg/appdef/impl_query_test.go
pkg/appdef/impl_structure_test.go
pkg/appdef/impl_tag.go
pkg/appdef/impl_tag_test.go
pkg/appdef/impl_type.go
pkg/appdef/impl_type_test.go
pkg/appdef/impl_unique.go
pkg/appdef/impl_unique_test.go
pkg/appdef/impl_view_test.go
pkg/appdef/impl_wdoc_test.go
pkg/appdef/impl_workspace.go
pkg/appdef/impl_workspace_test.go
pkg/appdef/interface_workspace.go
pkg/appdef/internal/slices/slices.go
pkg/appdef/internal/slices/slices_test.go

Resolves #3057 Daily Test failed on 24/12/2024 05:15

#3057 Daily Test failed on 24/12/2024 05:15

---

pkg/parser/impl_analyse.go
pkg/parser/impl_build.go

Resolves #3060 IsOperationAllowed works wrong on nested tables

#3060 IsOperationAllowed works wrong on nested tables

---

pkg/appdef/impl_appdef.go
pkg/appdef/impl_type.go
pkg/appdef/impl_workspace.go
pkg/appdef/internal/slices/slices.go
pkg/appdef/internal/slices/slices_test.go

Resolves #3067 fix DATA RACE in appdef types iteration

#3067 fix DATA RACE in appdef types iteration

---

pkg/appdef/filter/readme.md
pkg/processors/command/impl.go
pkg/processors/query/impl.go

Resolves #3089 implement workaround for legacy ACL rules

#3089 implement workaround for legacy ACL rules

---

pkg/coreutils/testwsdesc/wsdesc.go
pkg/iauthnzimpl/impl.go
pkg/iauthnzimpl/impl_test.go
pkg/processors/query/impl_test.go
pkg/sys/it/impl_signupin_test.go

Resolves #3100 roles from toke are not emitted on request in the user profile

#3100 roles from toke are not emitted on request in the user profile

---

pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #3106 fix vvm provide: add ITIme to istoragecache.Provide

#3106 fix vvm provide: add ITIme to istoragecache.Provide

---

pkg/coreutils/federation/impl.go
pkg/coreutils/federation/impl_test.go
pkg/coreutils/http.go
pkg/coreutils/types.go
pkg/processors/blobber/impl_write.go
pkg/state/teststate/impl.go
pkg/state/types.go
pkg/sys/it/impl_invite_test.go
pkg/sys/it/impl_test.go
pkg/sys/it/impl_uniques_test.go
pkg/sys/it/test_utils.go
pkg/sys/storages/impl_federation_cmd_storage.go
pkg/vit/impl_test.go

Resolves #3114 commandprocessor.CommandResponse.NewID int64 -> uint64

#3114 commandprocessor.CommandResponse.NewID int64 -> uint64

---

pkg/processors/blobber/impl_read.go
pkg/processors/blobber/impl_write.go
pkg/sys/it/impl_blob_test.go
pkg/sys/sys.vsql

Resolves #3121 fix handling errors on blob read

#3121 fix handling errors on blob read

---

pkg/processors/blobber/impl_read.go
pkg/processors/blobber/impl_write.go
pkg/router/impl_blob.go

Resolves #3123 log blob request url

#3123 log blob request url

---

pkg/appdef/examples/example_role_test.go
pkg/appdef/interface_operations.go
pkg/appdef/internal/acl/acl_test.go
pkg/appdef/internal/roles/role_test.go
pkg/appdef/utils_operation.go
pkg/appdef/utils_operation_test.go
pkg/goutils/set/set.go
pkg/goutils/set/set_test.go
pkg/istructsmem/internal/descr/example_test.go

Resolves #3126 appdef: include Activate/Deactivate to ACL operations

#3126 appdef: include Activate/Deactivate to ACL operations

---

pkg/sys/it/bug_test.go
pkg/sys/it/impl_changepassword_test.go
pkg/sys/workspace/impl.go
pkg/vit/utils.go

Resolves #3119 Fix "token issues for another application" errors during tests
Resolves #3098

#3119 Fix "token issues for another application" errors during tests

---

pkg/istructsmem/viewrecords-types.go

Resolves #3132 perftest: Performance degradation, 11.01

#3132 perftest: Performance degradation, 11.01

---

pkg/appdef/interface_operations.go
pkg/appdef/internal/rates/ratelimit_test.go

Resolves #3134 appdef: add Active/Deactivate to limitable opertaions

#3134 appdef: add Active/Deactivate to limitable opertaions

---

pkg/appparts/internal/acl/acl.go
pkg/appparts/internal/acl/acl_test.go

Resolves #3148 appparts: ACTIVATE/DEACTIVATE in IsOperationAllowed

#3148 appparts: ACTIVATE/DEACTIVATE in IsOperationAllowed

---

pkg/coreutils/federation/impl.go
pkg/in10n/interface.go
pkg/in10nmem/impl.go
pkg/router/impl_n10n.go
pkg/sys/storages/impl_view_records_storage.go

#3158 n10n: logging

---

pkg/in10n/impl.go
pkg/in10n/impl_test.go
pkg/in10nmem/impl.go
pkg/processors/command/impl.go
pkg/processors/command/provide.go
pkg/router/impl_n10n.go
pkg/sys/it/impl_n10n_test.go
pkg/sys/it/impl_vsqlupdate_test.go
pkg/vit/schemaTestApp1.vsql
pkg/vit/shared_cfgs.go

Resolves #3161 n10n: improve sse managing

#3161 n10n: improve sse managing

---

pkg/router/impl_n10n.go

Resolves #3166 n10n: use LogVerbose() util func

#3166 n10n: use LogVerbose() util func

---

pkg/appdef/internal/packages/package_test.go

Resolves #3168 fix Test_Packages()

#3168 fix Test_Packages()

---

pkg/vit/impl.go
pkg/vit/impl_vitcfg.go
pkg/vit/types.go
pkg/vit/utils.go

Resolves #3180 VIT: add subjects to login profile in shared config definition

#3180 VIT: add subjects to login profile in shared config definition

---

pkg/appparts/internal/acl/acl.go

Resolves #3191 IsOperationAllowed: deny -> additionally log wsid

#3191 IsOperationAllowed: deny -> additionally log wsid

---

pkg/iblobstoragestg/impl.go
pkg/istorage/mem/impl.go
pkg/istorage/tck.go
pkg/sys/it/impl_sqlquery_test.go
pkg/sys/sqlquery/impl.go
pkg/sys/sqlquery/provide.go

Resolves #3195 mem.InsertIfNotExists works wrong

#3195 mem.InsertIfNotExists works wrong

---

pkg/processors/oldacl/acl.go
pkg/processors/query/impl.go

Resolves #3202 old ACL: skip OperationKind_Select checking

#3202 old ACL: skip OperationKind_Select checking

---

pkg/iblobstoragestg/impl.go
pkg/iblobstoragestg/provide.go
pkg/istorage/interface.go

Resolves #3208 IAppStorageFactory and IAppStorageProvider: update contracts

#3208 IAppStorageFactory and IAppStorageProvider: update contracts

---

pkg/istoragecache/impl.go

Resolves #3210 ammend comments on funs of `istoragecache` package

#3210 ammend comments on funs of `istoragecache` package

---

pkg/router/impl_n10n.go

Resolves #3213 fix `sse message sent` verbose log

#3213 fix `sse message sent` verbose log

---

pkg/processors/command/impl.go
pkg/processors/oldacl/acl.go
pkg/processors/query/impl.go
pkg/sys/it/impl_verifier_test.go
pkg/sys/it/impl_workspace_test.go

Resolves #3221 ACL: first check new, then check old

#3221 ACL: first check new, then check old

---

pkg/processors/query/impl.go

Resolves #3223 ACL: select is denied -> do not return 403, just log.

#3223 ACL: select is denied -> do not return 403, just log.

---

pkg/processors/command/impl.go
pkg/processors/command/impl_test.go
pkg/sys/it/impl_test.go
pkg/vit/schemaTestApp1.vsql
pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #3149 Access to sys* fields

#3149 Access to sys* fields

---

pkg/coreutils/appwsid.go
pkg/ihttpimpl/impl.go
pkg/router/impl_http.go
pkg/router/impl_reply.go
pkg/router/impl_test.go
pkg/router/provide.go
pkg/router/types.go
pkg/vvm/impl_requesthandler.go
pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #3232 pseudoWSID->appWSID conversion VVM -> back to router (rollback #3188)

#3232 pseudoWSID->appWSID conversion VVM -> back to router (rollback #3188)

---

pkg/processors/query/impl.go
pkg/sys/it/impl_sqlquery_test.go
pkg/sys/sqlquery/impl.go

Resolves #3150 implement result authz on q.sys.SqlQuery

#3150 implement result authz on q.sys.SqlQuery

---

pkg/vit/impl_vitcfg.go
pkg/vit/types.go

Resolves #3248 VIT: expose `VITConfigOptFunc` type

#3248 VIT: expose `VITConfigOptFunc` type

---

pkg/sys/it/impl_cud_test.go
pkg/vit/schemaTestApp1.vsql
pkg/vit/shared_cfgs.go

Resolves #3252 implement a test that show the problem on unnaming the ref field in the result of a query

#3252 implement a test that show the problem on unnaming the ref field in the result of a query

---

pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #3266 Wire IVVMAppTTLStorage

#3266 Wire IVVMAppTTLStorage

---

cmd/vpm/ormtemplates/methods.gotmpl
cmd/vpm/ormtemplates/utils.gotmpl

3256 orm wrong id assigning on insert

---

cmd/vpm/ormtemplates/methods.gotmpl

3269 orm fix id assigning on insert

---

cmd/vpm/main_test.go
cmd/vpm/orm.go
cmd/vpm/ormtemplates/methods.gotmpl

Resolves #3277 fix orm template on creating a new CDoc value
Resolves #3271

#3277 fix orm template on creating a new CDoc value

---

pkg/coreutils/utils/consts.go
pkg/elections/README.md
pkg/vvm/ttlstorage/README.md
pkg/vvm/ttlstorage/impl.go
pkg/vvm/ttlstorage/impl_test.go
pkg/vvm/ttlstorage/provide.go
pkg/vvm/ttlstorage/types.go

3265 implement pkgvvmttlstorage

---

.github/workflows/ci-pkg-storage.yml

Resolves #3176 devops: cas, amazondb

#3176 devops: cas, amazondb

---

pkg/istorage/amazondb/README.md

test-amazon

---

pkg/vvm/builtin/clusterapp/provide.go
pkg/vvm/builtin/registryapp/provide.go
pkg/vvm/builtin/types.go
pkg/vvm/impl_builder.go

Resolves #3301 VIT: cache app ASTs across owned VIT configs

#3301 VIT: cache app ASTs across owned VIT configs

---

pkg/vit/impl.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #3311 VVM: eliminate VVMIdxType

#3311 VVM: eliminate VVMIdxType

---

pkg/vvm/provide.go
pkg/vvm/wire_gen.go

Resolves #3308 panic on no apps defied in VVM cfg

#3308 panic on no apps defied in VVM cfg

---

pkg/appparts/internal/acl/acl.go
pkg/appparts/internal/acl/acl_test.go

Resolves #3317 fix IsOperationAllowed error on OpKind_Select for view

#3317 fix IsOperationAllowed error on OpKind_Select for view

---

pkg/elections/README.md
pkg/elections/impl.go
pkg/elections/impl_test.go
pkg/elections/interface.go
pkg/elections/provide.go
pkg/elections/types.go
pkg/vvm/consts.go
pkg/vvm/impl_orch.go
pkg/vvm/impl_orch_test.go
pkg/vvm/storage/impl_elections.go
pkg/vvm/storage/impl_elections_test.go
pkg/vvm/storage/interface.go
pkg/vvm/storage/provide.go
pkg/vvm/types.go

Resolves #3326 elections does not work with cassandra\scylla

#3326 elections does not work with cassandra\scylla

---

pkg/vit/impl.go
pkg/vit/types.go
pkg/vvm/impl_orch.go
pkg/vvm/impl_orch_test.go

Resolves #3328 use orchestrated VVM in VIT

#3328 use orchestrated VVM in VIT

---

pkg/sys/invite/impl_initiatejoinworkspace.go
pkg/sys/it/impl_invite_test.go

Resolves #3330 Add some reqmd coverage labels

#3330 Add some reqmd coverage labels

---

pkg/elections/impl.go

Resolves #3345 do not log `renewing leadership` each 10 seconds

#3345 do not log `renewing leadership` each 10 seconds

---

pkg/vit/impl.go
pkg/vvm/impl_orch.go
pkg/vvm/impl_orch_test.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #3347 do not log we're no a leader after restart each millisecond

#3347 do not log we're no a leader after restart each millisecond

---

pkg/router/impl_test.go

Resolves #3350 Fix data race in TestClientDisconnect_FailedToWriteResponse()
Resolves #3348

#3350 Fix data race in TestClientDisconnect_FailedToWriteResponse()

---

pkg/elections/impl_test.go
pkg/elections/interface.go
pkg/elections/provide.go
pkg/elections/types.go
pkg/vvm/storage/interface.go
pkg/vvm/storage/provide.go
pkg/vvm/types.go

Resolves #3362 relocate `ITTLStorage` `vvm/storage` -> `elections`

#3362 relocate `ITTLStorage` `vvm/storage` -> `elections`

---

pkg/elections/README.md
pkg/elections/impl_test.go

Resolves #3365 elections: eliminate unneccesary dependencies

#3365 elections: eliminate unneccesary dependencies

---

.golangci.yml

need add unused linters

---

pkg/vvm/impl_orch.go

Resolves #3385 fix processKillThreshold reqmd mark

#3385 fix processKillThreshold reqmd mark

---

pkg/vvm/types.go

Resolves #3388 rename VVMConfig reqmd mark

#3388 rename VVMConfig reqmd mark

---

pkg/vvm/impl_orch_test.go
pkg/vvm/shutdowntest/iml_shutdown_test.go
pkg/vvm/test_utils.go

Resolves #3390 make TestAutomaticShutdownOnLeadershipLoss() be the single in the package

#3390 make TestAutomaticShutdownOnLeadershipLoss() be the single in the package

---

pkg/router/impl_apiv2.go
pkg/vvm/impl_orch.go
pkg/vvm/impl_orch_test.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

Resolves #3342 qpv2: fix paths in router

#3342 qpv2: fix paths in router

---

pkg/coreutils/test_utils.go

Resolves #3400 Expose fields of coreutils.MockIField

#3400 Expose fields of coreutils.MockIField

---

README.md

#3402 test issue

---

pkg/sys/collection/state_func.go
pkg/sys/it/impl_test.go
pkg/sys/sys.vsql

Resolves #3409 q.sys.State: return MaxRelevantOffset

#3409 q.sys.State: return MaxRelevantOffset

---

pkg/istorage/amazondb/impl.go
pkg/istorage/bbolt/impl.go
pkg/istorage/cas/impl.go
pkg/istorage/cas/impl_test.go
pkg/istorage/cas/provide.go
pkg/istorage/interface.go
pkg/istorage/mem/impl.go
pkg/istorage/tck.go
pkg/istoragecache/impl.go
pkg/istoragecache/impl_test.go
pkg/istoragecache/metrics.go
pkg/istructsmem/internal/teststore/store.go

3407 iappstoragequeryttl

---

pkg/bus/types.go
pkg/processors/query2/types.go
pkg/processors/query2/util.go
pkg/router/consts.go
pkg/router/impl_apiv2.go
pkg/vvm/impl_requesthandler.go

Resolves #3421 router: handle `/schemas` paths

#3421 router: handle `/schemas` paths

---

pkg/bus/types.go
pkg/processors/query2/types.go
pkg/processors/query2/util.go
pkg/router/impl_apiv2.go
pkg/vvm/impl_requesthandler.go

Resolves #3425 fix workspace and role QNames identification in Query Message

#3425 fix workspace and role QNames identification in Query Message

---

pkg/ielections/impl.go

Resolves #3427 improve IElections log messages

#3427 improve IElections log messages

---

pkg/coreutils/federation/impl.go
pkg/processors/query2/const.go
pkg/processors/query2/impl.go
pkg/processors/query2/impl_docs_handler.go
pkg/processors/query2/impl_query_handler.go
pkg/processors/query2/impl_schemas_handler.go
pkg/router/impl_apiv2.go
pkg/sys/it/impl_qpv2_test.go

Resolves #3341 GET `/schemas`: list app workspaces

#3341 GET `/schemas`: list app workspaces

---

pkg/processors/query2/impl_openapi.go
pkg/processors/query2/impl_openapi_schema.go

Resolves #3467 OpenAPI: reference issue

#3467 OpenAPI: reference issue

---

pkg/processors/query2/impl_openapi.go
pkg/processors/query2/impl_openapi_schema.go

Resolves #3470 OpenAPI: use role comment for schema description

#3470 OpenAPI: use role comment for schema description

---

pkg/processors/query2/impl_openapi.go

Resolves #3469 OpenApi: improve view schemas

#3469 OpenApi: improve view schemas

---

pkg/coreutils/objectreader.go
pkg/coreutils/objectreader_test.go

Resolves #3477 Wrong FieldsToMap behaviour on QName fields

#3477 Wrong FieldsToMap behaviour on QName fields

---

go.mod
go.sum
pkg/itokensjwt/impl.go
pkg/itokensjwt/provide.go
pkg/itokensjwt/types.go

Resolves #3482 update jwt tokens lib

#3482 update jwt tokens lib

---

pkg/processors/query2/impl.go
pkg/processors/query2/impl_docs_handler.go
pkg/sys/it/impl_qpv2_test.go

Resolves #3484 /docs: Add reqmd labels

#3484 /docs: Add reqmd labels

---

pkg/appdef/acl/provide.go
pkg/appdef/acl/provide_test.go
pkg/processors/query2/impl.go
pkg/processors/query2/impl_openapi.go
pkg/processors/query2/impl_schemas_role_handler.go
pkg/sys/it/impl_qpv2_test.go

Resolves #3487 /role: add reqmd references

#3487 /role: add reqmd references

---

.golangci.yml
pkg/iextengine/wazero/impl.go

#3505 fix linters

---

pkg/processors/query2/impl_openapi.go

Resolves #3507 revert reqmd tags

#3507 revert reqmd tags

---

pkg/isequencer/impl_test.go

3490 fix testsequencer

---

cmd/vpm/build.go
cmd/vpm/const.go
cmd/vpm/init.go
cmd/vpm/main_test.go

3512 vpm demand go 124 and tinygo 037

---

pkg/isequencer/impl.go
pkg/isequencer/provide.go
pkg/isequencer/types.go

Resolves #3525 fix TestISequencer_LongRecovery

#3525 fix TestISequencer_LongRecovery

---

pkg/isequencer/impl_test.go

Resolves #3530 fix TestSequencer
Resolves #3529

#3530 fix TestSequencer

---

pkg/router/impl_apiv2.go
pkg/router/impl_reply_v2.go
pkg/router/utils.go
pkg/sys/it/impl_qpv2_test.go

Resolves #3540 improve errors handling on auth/login

#3540 improve errors handling on auth/login

---

pkg/processors/query2/const.go
pkg/processors/query2/impl.go
pkg/processors/query2/impl_auth_login_handler.go
pkg/processors/query2/impl_cdocs_handler.go
pkg/processors/query2/impl_docs_handler.go
pkg/processors/query2/impl_query_handler.go
pkg/processors/query2/impl_schemas_handler.go
pkg/processors/query2/impl_schemas_role_handler.go
pkg/processors/query2/impl_schemas_roles_handler.go
pkg/processors/query2/impl_view_handler.go
pkg/processors/query2/types.go
pkg/processors/query2/util.go

Resolves #3543 QPv2: refactor IApiPathHandler

#3543 QPv2: refactor IApiPathHandler

---

pkg/processors/consts.go
pkg/processors/query2/const.go
pkg/processors/query2/impl.go
pkg/processors/query2/impl_auth_login_handler.go
pkg/processors/query2/impl_auth_refresh_handler.go
pkg/processors/query2/impl_openapi.go
pkg/processors/query2/impl_query_handler.go
pkg/processors/query2/impl_schemas_handler.go
pkg/processors/query2/impl_schemas_role_handler.go
pkg/processors/query2/impl_schemas_roles_handler.go
pkg/processors/query2/util.go
pkg/router/consts.go
pkg/router/impl_apiv2.go
pkg/sys/it/impl_qpv2_test.go

Resolves #3533 implement `/auth/refresh`

#3533 implement `/auth/refresh`

---

pkg/isequencer/impl_race_test.go
pkg/isequencer/impl_test.go
pkg/isequencer/isequencer_test.go
pkg/isequencer/provide.go

Resolves #3548 New should not wait for Actualize to finish

#3548 New should not wait for Actualize to finish

---

pkg/coreutils/federation/impl.go
pkg/coreutils/http.go
pkg/coreutils/types.go
pkg/processors/query2/impl.go
pkg/processors/query2/impl_auth_login_handler.go
pkg/processors/query2/impl_auth_refresh_handler.go
pkg/processors/query2/impl_query_handler.go
pkg/processors/query2/types.go
pkg/router/consts.go
pkg/router/impl_apiv2.go
pkg/sys/it/impl_qpv2_test.go

Resolves #3545 `/auth/login`: federation post in QPv2 to registry app

#3545 `/auth/login`: federation post in QPv2 to registry app

---

pkg/isequencer/isequencer_test.go

Resolves #3552 fix TestISequencer_Start
Resolves #3551

#3552 fix TestISequencer_Start

---

pkg/istorage/mem/impl.go
pkg/istorage/mem/provide.go

Resolves #3447 fix data race in vvm/TestBasic/LeadershipCollision

#3447 fix data race in vvm/TestBasic/LeadershipCollision

---

pkg/processors/query2/impl_auth_login_handler.go
pkg/processors/query2/impl_auth_refresh_handler.go
pkg/processors/query2/impl_openapi.go
pkg/processors/query2/impl_schemas_handler.go
pkg/processors/query2/impl_schemas_role_handler.go
pkg/processors/query2/impl_schemas_roles_handler.go
pkg/router/impl_apiv2.go
pkg/router/impl_test.go
pkg/sys/it/impl_cpv2_test.go
pkg/sys/it/impl_qpv2_test.go
pkg/sys/it/schema.json

Resolves #3495 APIv2 paths: update router request handler

#3495 APIv2 paths: update router request handler

---

pkg/isequencer/impl.go
pkg/isequencer/impl_test.go

Resolves #3572 sequences: toBeFlushed is not cleared

#3572 sequences: toBeFlushed is not cleared

---

pkg/isequencer/design.md

Resolves #3575 relocate documentation from voedger-internals

#3575 relocate documentation from voedger-internals

---

pkg/coreutils/http.go
pkg/processors/command/impl.go
pkg/sys/it/impl_cpv2_test.go
pkg/sys/it/impl_test.go

Resolves #3417 CP: handle `/v2/.../commands`

#3417 CP: handle `/v2/.../commands`

---

pkg/isequencer/design.md
pkg/isequencer/isequencer_test.go

Resolves #3581 minor update sequencer design

#3581 minor update sequencer design

---

pkg/isequencer/consts.go
pkg/isequencer/design.md
pkg/isequencer/impl.go
pkg/isequencer/impl_test.go
pkg/isequencer/isequencer_test.go
pkg/isequencer/provide.go
pkg/isequencer/test_utils.go
pkg/isequencer/types.go

Resolves #3583 amend sequencer tests

#3583 amend sequencer tests

---

pkg/isequencer/impl.go
pkg/isequencer/isequencer_test.go

Resolves #3585 fix TestISequencer_MultipleActualizes()
Resolves #3580

#3585 fix TestISequencer_MultipleActualizes()

---

pkg/isequencer/impl_test.go
pkg/isequencer/isequencer_test.go
pkg/isequencer/test_utils.go

Resolves #3588 fix TestSequencer_Start
Resolves #3587

#3588 fix TestSequencer_Start

---

pkg/appparts/internal/seqstorage/impl.go
pkg/isequencer/interface.go
pkg/vvm/storage/impl_seqstorage.go
pkg/vvm/storage/impl_seqstorage_test.go
pkg/vvm/storage/interface.go

Resolves #3573 improve saving batch of Numbers in ISeqStorage

#3573 improve saving batch of Numbers in ISeqStorage

---

pkg/isequencer/test_utils.go
pkg/isequencer/types.go

Resolves #3598 Fix TestISequencer_Flush()
Resolves #3596

#3598 Fix TestISequencer_Flush()

---

pkg/router/impl_apiv2.go
pkg/sys/it/impl_signupin_test.go
pkg/vit/utils.go

Resolves #3565 CPv2: handle `/devices`

#3565 CPv2: handle `/devices`

---

pkg/sys/it/race_cud_test.go

#3618 minor refactor

---

pkg/appdef/consts.go
pkg/processors/query2/impl_openapi.go
pkg/processors/query2/impl_schemas_handler.go
pkg/processors/query2/impl_schemas_role_handler.go
pkg/processors/query2/impl_schemas_roles_handler.go
pkg/processors/query2/util.go
pkg/sys/it/impl_qpv2_test.go

Resolves #3625 schemas must support sys.Developer

#3625 schemas must support sys.Developer

---

pkg/processors/query2/impl_openapi.go

Resolves #3630 OpenAPI: arg schemas

#3630 OpenAPI: arg schemas

---

pkg/vvm/impl_cfg.go

Resolves #3641 temporary set SequencesTrustLevel_2

#3641 temporary set SequencesTrustLevel_2

---

pkg/appparts/internal/seqstorage/impl.go
pkg/isequencer/interface.go
pkg/vvm/storage/impl_seqstorage.go
pkg/vvm/storage/impl_seqstorage_test.go

Resolves #3647 refactor IVVMSeqStorageAdapter

#3647 refactor IVVMSeqStorageAdapter

---

pkg/appparts/internal/seqstorage/impl.go
pkg/appparts/internal/seqstorage/impl_test.go
pkg/vvm/storage/impl_seqstorage_test.go

Resolves #3650 consider wlogoffset in batcher

#3650 consider wlogoffset in batcher

---

pkg/appparts/internal/seqstorage/impl.go
pkg/appparts/internal/seqstorage/impl_test.go
pkg/isequencer/interface.go
pkg/vvm/storage/impl_seqstorage.go
pkg/vvm/storage/impl_seqstorage_test.go
pkg/vvm/storage/provide.go

Resolves #3652 do not store PartitionID in VVMSeqStorageAdapter

#3652 do not store PartitionID in VVMSeqStorageAdapter

---

pkg/vvm/storage/impl_seqstorage.go
pkg/vvm/storage/types.go

#3657 respect linter

---

pkg/iauthnzimpl/impl_test.go
pkg/istructs/interface.go
pkg/istructsmem/appstruct-types.go
pkg/istructsmem/impl.go
pkg/sys/workspace/impl.go
pkg/vvm/types.go

Resolves #3659 Handle QNameID in IAppStructs

#3659 Handle QNameID in IAppStructs

---

pkg/registry/appws.vsql
pkg/registry/impl_createlogin.go
pkg/router/impl_apiv2.go
pkg/sys/it/impl_cpv2_test.go
pkg/sys/it/impl_signupin_test.go

Resolves #3668 fix users and devices reqmd packages

#3668 fix users and devices reqmd packages

---

pkg/processors/query2/impl_auth_login_handler.go
pkg/processors/query2/impl_openapi.go
pkg/processors/query2/impl_queryparams.go
pkg/processors/query2/impl_queryparams_test.go
pkg/router/impl_apiv2.go
pkg/sys/it/impl_qpv2_test.go
pkg/sys/it/schema.json

Resolves #3667 QPv2: "?arg" -> "?args"

#3667 QPv2: "?arg" -> "?args"

---

pkg/processors/query2/const.go
pkg/processors/query2/impl_openapi.go
pkg/processors/query2/impl_schemas_role_handler.go
pkg/sys/it/impl_qpv2_test.go

Resolves #3631 OpenAPI: show `/users/` and '/devices/` to `sys.Developer`

#3631 OpenAPI: show `/users/` and '/devices/` to `sys.Developer`

---

pkg/vvm/impl_cfg.go

Resolves #3642 set SequencesTrustLevel_0

#3642 set SequencesTrustLevel_0

---

pkg/goutils/testingu/mocktime.go
pkg/ielections/impl_testsuite.go
pkg/vvm/storage/impl_electionsbydrivers_test.go

Resolves #3679 fix Dynamo DB Elections test

#3679 fix Dynamo DB Elections test

---

pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/types.go

Resolves #3476 issue with grant on fields

#3476 issue with grant on fields

---

pkg/processors/query2/impl.go
pkg/processors/query2/impl_auth_login_handler.go
pkg/processors/query2/impl_auth_refresh_handler.go
pkg/processors/query2/impl_openapi.go
pkg/router/impl_apiv2.go
pkg/sys/it/impl_qpv2_test.go

Resolves #3684 change package authnz

#3684 change package authnz

---

pkg/parser/const.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/sql_example_syspkg/system.vsql

Resolves #3686 appdef: distinguish BLOB fields

#3686 appdef: distinguish BLOB fields

---

pkg/processors/query2/impl_cdocs_handler.go
pkg/processors/query2/impl_docs_handler.go
pkg/processors/query2/impl_query_handler.go
pkg/processors/query2/impl_view_handler.go
pkg/processors/query2/types.go
pkg/processors/query2/util.go
pkg/sys/it/impl_qpv2_test.go

Resolves #3696 APIv2 read from view hangs

#3696 APIv2 read from view hangs

---

pkg/processors/query2/const.go
pkg/processors/query2/impl_openapi.go
pkg/processors/query2/impl_openapi_schema.go
pkg/vit/schemaTestApp1.vsql

Resolves #3664 BLOB fields: generate OpenAPI endoints

#3664 BLOB fields: generate OpenAPI endoints

---

pkg/sys/invite/consts.go

Resolves #3716 allow re-invite on `ToBeJoined` state

#3716 allow re-invite on `ToBeJoined` state

---

pkg/processors/query2/const.go
pkg/processors/query2/impl_auth_login_handler.go
pkg/processors/query2/impl_auth_refresh_handler.go
pkg/router/consts.go
pkg/router/impl_apiv2.go
pkg/sys/it/impl_cpv2_test.go
pkg/sys/it/impl_qpv2_test.go
pkg/vit/utils.go

Resolves #3713 API payload JSON fields naming conventions

#3713 API payload JSON fields naming conventions

---

pkg/registry/impl_changepassword.go
pkg/registry/utils.go

#3718 minor refactor

---

pkg/coreutils/http.go

Resolves #3729 HTTPClient: WithDeadlineOn503 request optional func

#3729 HTTPClient: WithDeadlineOn503 request optional func

---

go.mod

Resolves #3733 minor go.mod update

#3733 minor go.mod update

---

pkg/router/consts.go
pkg/router/impl_apiv2.go
pkg/sys/it/impl_n10n_test.go

Resolves #3766 APIv2 notifications: implement unsubscribe

#3766 APIv2 notifications: implement unsubscribe

---

pkg/processors/query2/impl_auth_login_handler.go
pkg/vit/utils.go

Resolves #3756 login: status when wsid == 0

#3756 login: status when wsid == 0

---

pkg/parser/errors.go
pkg/parser/impl_analyse.go
pkg/parser/impl_build.go
pkg/parser/impl_test.go
pkg/parser/types.go

Resolves #2334 parser: wrong error message on missing `RETURNS`

#2334 parser: wrong error message on missing `RETURNS`

---

pkg/processors/command/impl_apiv2.go
pkg/sys/it/impl_cpv2_test.go

Resolves #3781 CPv2: fix typo in error message

#3781 CPv2: fix typo in error message

---

pkg/sys/it/impl_jobs_test.go

Resolves #3819 minor compilation fix

#3819 minor compilation fix

---

pkg/iauthnzimpl/impl.go
pkg/itokens-payloads/types.go
pkg/registry/appws.vsql
pkg/registry/impl_issueprincipaltoken.go
pkg/registry/impl_updateglobalroles.go
pkg/sys/authnz/consts.go
pkg/sys/it/impl_signupin_test.go

Resolves #3824 Use GlobalRoles in the PrincipalToken and the authenticator

#3824 Use GlobalRoles in the PrincipalToken and the authenticator

---

pkg/registry/appws.vsql
pkg/registry/impl_updateglobalroles.go

Resolves #3827 fix reqman link

#3827 fix reqman link

---

pkg/coreutils/maps_test.go
pkg/coreutils/test_utils.go

Resolves #3839 improve coreutils/maps_test.go

#3839 improve coreutils/maps_test.go

---

pkg/coreutils/objectreader_test.go

Resolves #3841 implement unit test for coreutils `CUDsToMap()`

#3841 implement unit test for coreutils `CUDsToMap()`

---

pkg/processors/command/impl_test.go

Resolves #3851 Put in order processors/command/TestAuth

#3851 Put in order processors/command/TestAuth

---

pkg/in10nmem/impl.go

Resolves #3855 in10nme: Fix incorrect break within switch in

#3855 in10nme: Fix incorrect break within switch in

---

pkg/processors/blobber/impl.go
pkg/processors/blobber/impl_read.go
pkg/processors/blobber/impl_requesthandler.go
pkg/processors/blobber/interface.go
pkg/processors/blobber/provide.go
pkg/processors/blobber/types.go

Resolves #3909 internals: improve documentation for read blob

#3909 internals: improve documentation for read blob

---

pkg/processors/actualizers/actualizers.go
pkg/processors/actualizers/async.go
pkg/processors/actualizers/async_test.go
pkg/processors/actualizers/consts.go

https://untill.atlassian.net/browse/AIR-1246

set actualizer retry delay on error to 100ms in tests

---

pkg/coreutils/federation/impl.go
pkg/coreutils/federation/interface.go
pkg/coreutils/federation/types.go
pkg/coreutils/http.go
pkg/registry/impl_invokecreateworkspaceid.go
pkg/registry/provide.go
pkg/sys/workspace/impl.go
pkg/sys/workspace/impl_buildws.go
pkg/sys/workspace/provide.go
pkg/sys/workspace/types.go

[AIR-1262] retry on 503 during Workspace init
https://untill.atlassian.net/browse/AIR-1262

retry on 503 during Workspace init

---

pkg/sys/it/impl_vsqlupdate_test.go

Resolves #3946 skip TestDirectUpdateManyTypes

skip TestDirectUpdateManyTypes

---

pkg/processors/actualizers/async.go
pkg/processors/actualizers/consts.go

[AIR-1283] eliminate wait for app deploy on actualizers launch
https://untill.atlassian.net/browse/AIR-1283

eliminate wait for app deploy on actualizers launch

---

pkg/appparts/internal/actualizers/actualizers.go
pkg/sys/workspace/impl.go
pkg/vit/impl.go

Resolves #3971 Fix actualizers shutdown workflow

Fix actualizers shutdown workflow

---

pkg/processors/query2/impl_view_handler.go
pkg/sys/it/impl_qpv2_test.go
pkg/sys/it/impl_signupin_test.go

Resolves #3959 fix TestQueryProcessor2_Views/ACL_test

#3959 fix TestQueryProcessor2_Views/ACL_test

---

pkg/appparts/internal/actualizers/actualizers.go
pkg/appparts/internal/actualizers/actualizers_test.go

Resolves #3978 improve PartitionActualizers start\stop workflow

improve PartitionActualizers start\stop workflow

---

.github/workflows/ci-full.yml
.github/workflows/ci-pkg-cmd.yml
.github/workflows/ci-pkg-cmd_pr.yml
.github/workflows/ci_amazon.yml
.github/workflows/ci_cas.yml
.github/workflows/cp.yml

Resolves #3997 use main branch instead of master in ci-action

use main branch instead of master in ci-action

---

pkg/processors/query2/impl.go

Resolves #3975 QPv2: error 500 on invalid `keys` query constraint

QPv2: error 500 on invalid `keys` query constraint

---

pkg/sys/it/impl_bootstrap_test.go
pkg/sys/it/impl_recovery_test.go
pkg/vit/impl.go
pkg/vit/utils.go
pkg/vvm/impl_cfg.go
pkg/vvm/impl_orch_test.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

[AIR-1377] voedger: provide the actual time to the storage provider
https://untill.atlassian.net/browse/AIR-1377

voedger: provide the actual time to the storage provider

---

pkg/router/impl_test.go

Resolves #3406 fix TestClientDisconnect_FailedToWriteResponse()

fix TestClientDisconnect_FailedToWriteResponse()

---

pkg/coreutils/federation/impl.go
pkg/coreutils/federation/impl_test.go
pkg/coreutils/federation/utils.go
pkg/coreutils/http.go
pkg/coreutils/types.go

Resolves #4030 eliminate coreutils.FuncError

eliminate coreutils.FuncError

---

pkg/coreutils/federation/impl.go
pkg/coreutils/federation/impl_test.go
pkg/coreutils/http.go

Resolves #4032 http: deny response discarding on GET requests

http: deny response discarding on GET requests

---

pkg/bus/utils.go
pkg/bus/utils_test.go
pkg/coreutils/federation/impl_test.go
pkg/coreutils/federation/utils.go
pkg/coreutils/syserror.go
pkg/coreutils/types.go
pkg/processors/blobber/impl_write.go
pkg/processors/command/impl_test.go
pkg/sys/it/impl_federationcmdstorage_test.go
pkg/sys/it/impl_httpconventions_test.go
pkg/vit/impl.go

Resolves #4039 move SysError from Command response to Func response

move SysError from Command response to Func response

---

pkg/coreutils/federation/impl_test.go
pkg/coreutils/federation/utils.go
pkg/coreutils/http.go
pkg/coreutils/types.go

Resolves #4037 refactor\improve funcs response

refactor\improve funcs response

---

pkg/appparts/impl.go
pkg/goutils/retry/types.go

[AIR-1463] use retrier on AppPartition borrowing awaiting
https://untill.atlassian.net/browse/AIR-1463

use retrier on AppPartition borrowing awaiting

---

pkg/coreutils/consts.go
pkg/coreutils/http.go
pkg/coreutils/http_test.go
pkg/coreutils/types.go

[AIR-1466] use retrier on HTTP requests sending
https://untill.atlassian.net/browse/AIR-1466

use retrier on HTTP requests sending

---

pkg/processors/actualizers/actualizers.go
pkg/processors/actualizers/async.go
pkg/processors/actualizers/async_test.go
pkg/processors/actualizers/consts.go
pkg/processors/actualizers/impl_test.go
pkg/processors/actualizers/interface.go
pkg/processors/actualizers/types.go
pkg/vit/impl.go
pkg/vvm/impl_cfg.go
pkg/vvm/provide.go
pkg/vvm/types.go
pkg/vvm/wire_gen.go

[AIR-1467] use retrier in async actualizers
https://untill.atlassian.net/browse/AIR-1467

use retrier in async actualizers

---

pkg/router/impl_apiv2.go

Resolves #4052 APIv2: accept OPTIONS method

APIv2: accept OPTIONS method

---

pkg/coreutils/http.go
pkg/coreutils/http_test.go

[AIR-1485] voedger: deny `WithSkipRetryOn503` with `WithMaxRetryDurationOn503`
https://untill.atlassian.net/browse/AIR-1485

voedger: deny `WithSkipRetryOn503` with `WithMaxRetryDurationOn503`

---

pkg/coreutils/federation/impl.go

Resolves #4059 fix default opt funcs possible damage

fix default opt funcs possible damage

---

pkg/bus/utils.go
pkg/coreutils/http.go

Resolves #4051 fix `panic: send timeout expired`
Resolves #4050

fix `panic: send timeout expired`

---

pkg/sys/it/reverseproxy_test.go
pkg/vit/shared_cfgs.go

Resolves #4078 get rid of `it.TestServicePort`

get rid of `it.TestServicePort`

---

pkg/bus/utils.go
pkg/bus/utils_test.go
pkg/coreutils/utils.go
pkg/coreutils/utils_test.go
pkg/processors/command/impl_test.go
pkg/processors/query/impl_test.go
pkg/processors/query/operator-send-to-bus-impl_test.go
pkg/processors/query/query-params-impl_test.go
pkg/sys/collection/collection_test.go
pkg/vit/internal/utils.go
pkg/vit/utils.go

Resolves #4130 move `coreutils.IsDebug` to `vit/internals`

move `coreutils.IsDebug` to `vit/internals`

---

.augment/rules/generate-readme.md
.gitignore
pkg/goutils/README.md

[AIR-1592] Voedger: implement Augment AI manual rule for generate README.md
https://untill.atlassian.net/browse/AIR-1592

Voedger: implement Augment AI manual rule for generate README.md

---

pkg/goutils/cobrau/README.md
pkg/goutils/cobrau/catch_interrupt.go
pkg/goutils/cobrau/cobrau_test.go
pkg/goutils/cobrau/example_test.go

Resolves #4132 implement unit tests and example for goutils/cobrau

implement unit tests and example for goutils/cobrau

---

.github/workflows/ctool-integration-test.yml
cmd/ctool/README.md
cmd/ctool/scripts/drafts/ce/setup-passwordless-sudo.sh

[AIR-1554] perftest-to-ctool: fix voedger ctool
https://untill.atlassian.net/browse/AIR-1554

perftest-to-ctool: fix voedger ctool

---

pkg/sys/it/impl_test.go
pkg/sys/it/test_utils.go
pkg/vit/utils.go

Resolves #4167 VIT: implement WaitForOffset util func

VIT: implement WaitForOffset util func

---

pkg/sys/it/impl_verifier_test.go
pkg/sys/verifier/errors.go
pkg/sys/verifier/impl.go
pkg/sys/verifier/utils.go

[AIR-1771] return user-firendly error message if verification token has expired
https://untill.atlassian.net/browse/AIR-1771

[AIR-1771] return user-firendly error message if verification token has expired
